// Generated by `npm run types:gen` — do not edit manually.

// This file has been generated by Specta. Do not edit this file manually.
export type AppErrorCode = "game_running" | "invalid_path" | "game_not_found" | "preset_not_found" | "io_error" | "validation" | "other";

export type AppInvokeError = {
	code: AppErrorCode,
	message: string,
};

export type ApplyResult = ApplyResult_Serialize | ApplyResult_Deserialize;

export type ApplyResult_Deserialize = {
	post_apply_warning?: string | null,
	applied_input_lines?: number[] | null,
	backup_id: string,
	changed_files: string[],
	diff: ConfigDiffEntry[],
	/**  Current config directory after reconcile (may differ from the profile-stored path). */
	effective_config_dir: string | null,
};

export type ApplyResult_Serialize = {
	post_apply_warning?: string | null,
	applied_input_lines?: number[] | null,
	backup_id: string,
	changed_files: string[],
	diff: ConfigDiffEntry[],
	/**  Current config directory after reconcile (may differ from the profile-stored path). */
	effective_config_dir?: string | null,
};

export type BackupInfo = BackupInfo_Serialize | BackupInfo_Deserialize;

export type BackupInfo_Deserialize = {
	name?: string | null,
	source_dir?: string | null,
	id: string,
	created_at: string,
	files: string[],
};

export type BackupInfo_Serialize = {
	name?: string | null,
	source_dir?: string | null,
	id: string,
	created_at: string,
	files: string[],
};

export type ChangeIssue = {
	code: string,
	severity: string,
	message: string,
};

export type ChangeOperation = {
	id: string,
	group: string,
	file: string,
	section: string,
	key: string,
	before: string | null,
	after: string | null,
	kind: string,
};

export type ConfigDiffEntry = {
	file: string,
	section: string,
	key: string,
	old_value: string | null,
	new_value: string,
};

export type ConfigResetResult = {
	backup_id: string,
	deleted_files: string[],
};

export type CrashReportEntry = {
	id: string,
	created_at: string,
	kind: CrashReportKind,
	message: string,
	stack: string | null,
	component_stack: string | null,
	url: string | null,
	app_version: string,
};

export type CrashReportKind = "error_boundary" | "uncaught" | "unhandled_rejection";

export type CrashReportPayload = {
	kind: CrashReportKind,
	message: string,
	stack: string | null,
	component_stack: string | null,
	url: string | null,
	app_version: string,
};

export type CustomChanges = {
	files: { [key in string]: { [key in string]: { [key in string]: string } } },
	removals?: { [key in string]: { [key in string]: string[] } },
};

export type DiagnosticReport = {
	game_id: string,
	config_dir: string,
	expected_dir: string,
	status: string,
	changes: ChangeOperation[],
	checked_at: string,
	message: string | null,
};

export type GameConfig = {
	config_dir: string,
	files: { [key in string]: IniFileData },
};

export type GameOverride = GameOverride_Serialize | GameOverride_Deserialize;

export type GameOverride_Deserialize = {
	metadata?: PresetMetadata | null,
	input_updates?: InputUpdate_Deserialize[] | null,
	game_id: string,
	name: string,
	files: { [key in string]: { [key in string]: { [key in string]: string } } },
	removals?: { [key in string]: { [key in string]: string[] } },
};

export type GameOverride_Serialize = {
	metadata?: PresetMetadata | null,
	input_updates?: InputUpdate_Serialize[] | null,
	game_id: string,
	name: string,
	files: { [key in string]: { [key in string]: { [key in string]: string } } },
	removals: { [key in string]: { [key in string]: string[] } },
};

export type GameParameter = {
	key: string,
	section: string,
	file: string,
	value: string,
	title: string,
	description: string,
	impact: string,
	category: string,
	min: string | null,
	max: string | null,
	in_game_label: string | null,
	value_hint: string | null,
	value_type: string,
	known: boolean,
	editable?: boolean,
	present_in_ini?: boolean,
	default_value?: string | null,
	/**
	 *  Interactive control type in the manual editor: "slider" | "toggle" | "select" | "stepper" | "text".
	 *  None — frontend infers from value_type/min/max.
	 */
	ui_control?: string | null,
	/**  Step for slider/stepper. */
	step?: string | null,
	/**  Options for select. */
	options?: ParameterOption[] | null,
	/**  Author-recommended value (shown as hint/button). */
	recommended?: string | null,
	/**  Catalog flag for Advanced Editor «Recommended» filter. */
	catalog_recommended?: boolean,
	/**  UE scalability preset tier breakdown (sg.*Quality only). */
	tier_hint?: string | null,
	/**  Description tier: human | semi | auto (from catalog builder). */
	description_quality?: string | null,
};

export type GameProfile = GameProfile_Serialize | GameProfile_Deserialize;

export type GameProfile_Deserialize = {
	gpu_adapter_id?: string | null,
	launch_target?: LaunchTarget_Deserialize | null,
	id: string,
	name: string,
	source: string,
	install_dir: string,
	config_dir: string | null,
	exe_name: string | null,
	is_ue: boolean,
	possible_ue?: boolean,
	cover_url?: string | null,
	custom_cover?: string | null,
	build_id?: string | null,
	engine_family?: string,
	engine_version?: string | null,
};

export type GameProfile_Serialize = {
	gpu_adapter_id?: string | null,
	launch_target?: LaunchTarget_Serialize | null,
	id: string,
	name: string,
	source: string,
	install_dir: string,
	config_dir: string | null,
	exe_name: string | null,
	is_ue: boolean,
	possible_ue: boolean,
	cover_url: string | null,
	custom_cover: string | null,
	build_id: string | null,
	engine_family: string,
	engine_version: string | null,
};

export type GpuCapabilities = GpuCapabilities_Serialize | GpuCapabilities_Deserialize;

export type GpuCapabilities_Deserialize = {
	adapter_id?: string | null,
	dedicated_memory_mb?: number | null,
	shared_memory_mb?: number | null,
	ray_tracing_status?: string | null,
	selection_warning?: string | null,
	name: string,
	vendor: GpuVendor,
	/**  DLSS / DLAA — GeForce RTX 20 series and newer (Tensor Cores). */
	supports_dlss: boolean,
	/**  DLSS Frame Generation — RTX 40 series and newer. */
	supports_dlss_fg: boolean,
	/**  Hardware ray tracing in UE — GeForce RTX 20+. */
	supports_ray_tracing: boolean,
};

export type GpuCapabilities_Serialize = {
	adapter_id?: string | null,
	dedicated_memory_mb?: number | null,
	shared_memory_mb?: number | null,
	ray_tracing_status?: string | null,
	selection_warning?: string | null,
	name: string,
	vendor: GpuVendor,
	/**  DLSS / DLAA — GeForce RTX 20 series and newer (Tensor Cores). */
	supports_dlss: boolean,
	/**  DLSS Frame Generation — RTX 40 series and newer. */
	supports_dlss_fg: boolean,
	/**  Hardware ray tracing in UE — GeForce RTX 20+. */
	supports_ray_tracing: boolean,
};

export type GpuVendor = "nvidia" | "amd" | "intel" | "unknown";

export type IniFileData = {
	sections: { [key in string]: { [key in string]: string } },
};

export type InputDocument = {
	revision: string,
	entries: InputEntry[],
	source_path?: string,
	file_state?: InputFileState,
	custom_settings_path?: string | null,
};

export type InputEntry = {
	id: string,
	line: number,
	key: string,
	value: string,
	fields: { [key in string]: string },
	axis_properties?: { [key in string]: string } | null,
	editable: boolean,
	reason: string | null,
};

export type InputFileState = "missing" | "empty" | "no_classic_bindings" | "bindings";

export type InputUpdate = InputUpdate_Serialize | InputUpdate_Deserialize;

export type InputUpdate_Deserialize = {
	id?: string | null,
	line: number,
	expected: string,
	value: string,
};

export type InputUpdate_Serialize = {
	id?: string | null,
	line: number,
	expected: string,
	value: string,
};

export type LaunchResult = LaunchResult_Serialize | LaunchResult_Deserialize;

export type LaunchResult_Deserialize = {
	launcher: string,
	detail: string,
	warning: string | null,
};

export type LaunchResult_Serialize = {
	launcher: string,
	detail: string,
	warning?: string | null,
};

export type LaunchTarget = LaunchTarget_Serialize | LaunchTarget_Deserialize;

export type LaunchTarget_Deserialize = {
	working_dir?: string | null,
	kind: string,
	value: string,
};

export type LaunchTarget_Serialize = {
	working_dir?: string | null,
	kind: string,
	value: string,
};

export type ParameterOption = {
	value: string,
	label: string,
};

export type PrepareRequest = PrepareRequest_Serialize | PrepareRequest_Deserialize;

export type PrepareRequest_Deserialize = {
	game_id: string,
	config_dir: string,
	changes?: CustomChanges,
	backup_id?: string | null,
	restore_files?: string[],
	input_updates?: InputUpdate_Deserialize[],
	input_revision?: string | null,
	restore_origin_backup_id?: string | null,
	preset_metadata?: PresetMetadata | null,
};

export type PrepareRequest_Serialize = {
	game_id: string,
	config_dir: string,
	changes: CustomChanges,
	backup_id: string | null,
	restore_files: string[],
	input_updates: InputUpdate_Serialize[],
	input_revision: string | null,
	restore_origin_backup_id: string | null,
	preset_metadata: PresetMetadata | null,
};

export type PreparedChanges = {
	id: string,
	game_id: string,
	config_dir: string,
	operations: ChangeOperation[],
	issues: ChangeIssue[],
	revisions: { [key in string]: string | null },
};

export type PresetMetadata = {
	format_version?: number,
	mode?: string,
	description?: string,
	source_game_id?: string,
	source_game_name?: string,
	game_build?: string | null,
	engine_family?: string | null,
	engine_version?: string | null,
	gpu_vendor?: string | null,
	min_dedicated_memory_mb?: number | null,
	requires_ray_tracing?: boolean,
};

export type ScalabilityLimits = {
	groups: { [key in string]: number },
	global_max: number,
	sources: string[],
};

export type ScreenResolution = {
	width: number,
	height: number,
};
