// Generated by `npm run types:gen` — do not edit manually.

// This file has been generated by Specta. Do not edit this file manually.
export type AppErrorCode = "game_running" | "invalid_path" | "game_not_found" | "preset_not_found" | "io_error" | "validation" | "other";

export type AppInvokeError = {
	code: AppErrorCode,
	message: string,
};

export type ApplyResult = ApplyResult_Serialize | ApplyResult_Deserialize;

export type ApplyResult_Deserialize = {
	backup_id: string,
	changed_files: string[],
	diff: ConfigDiffEntry[],
	/**  Current config directory after reconcile (may differ from the profile-stored path). */
	effective_config_dir: string | null,
};

export type ApplyResult_Serialize = {
	backup_id: string,
	changed_files: string[],
	diff: ConfigDiffEntry[],
	/**  Current config directory after reconcile (may differ from the profile-stored path). */
	effective_config_dir?: string | null,
};

export type BackupInfo = {
	id: string,
	created_at: string,
	files: string[],
};

export type ConfigDiffEntry = {
	file: string,
	section: string,
	key: string,
	old_value: string | null,
	new_value: string,
};

export type ConfigResetResult = {
	backup_id: string,
	deleted_files: string[],
};

export type GameConfig = {
	config_dir: string,
	files: { [key in string]: IniFileData },
};

export type GameOverride = {
	game_id: string,
	name: string,
	files: { [key in string]: { [key in string]: { [key in string]: string } } },
	removals?: { [key in string]: { [key in string]: string[] } },
};

export type GameParameter = {
	key: string,
	section: string,
	file: string,
	value: string,
	title: string,
	description: string,
	impact: string,
	category: string,
	min: string | null,
	max: string | null,
	in_game_label: string | null,
	value_hint: string | null,
	value_type: string,
	known: boolean,
	editable?: boolean,
	present_in_ini?: boolean,
	default_value?: string | null,
	/**
	 *  Interactive control type in the manual editor: "slider" | "toggle" | "select" | "stepper" | "text".
	 *  None — frontend infers from value_type/min/max.
	 */
	ui_control?: string | null,
	/**  Step for slider/stepper. */
	step?: string | null,
	/**  Options for select. */
	options?: ParameterOption[] | null,
	/**  Author-recommended value (shown as hint/button). */
	recommended?: string | null,
	/**  Catalog flag for Advanced Editor «Recommended» filter. */
	catalog_recommended?: boolean,
	/**  UE scalability preset tier breakdown (sg.*Quality only). */
	tier_hint?: string | null,
	/**  Description tier: human | semi | auto (from catalog builder). */
	description_quality?: string | null,
};

export type GameProfile = {
	id: string,
	name: string,
	source: string,
	install_dir: string,
	config_dir: string | null,
	exe_name: string | null,
	is_ue: boolean,
	possible_ue?: boolean,
	cover_url?: string | null,
	custom_cover?: string | null,
	build_id?: string | null,
	engine_family?: string,
	engine_version?: string | null,
};

export type GpuCapabilities = {
	name: string,
	vendor: GpuVendor,
	/**  DLSS / DLAA — GeForce RTX 20 series and newer (Tensor Cores). */
	supports_dlss: boolean,
	/**  DLSS Frame Generation — RTX 40 series and newer. */
	supports_dlss_fg: boolean,
	/**  Hardware ray tracing in UE — GeForce RTX 20+. */
	supports_ray_tracing: boolean,
};

export type GpuVendor = "nvidia" | "amd" | "intel" | "unknown";

export type IniFileData = {
	sections: { [key in string]: { [key in string]: string } },
};

export type LaunchResult = LaunchResult_Serialize | LaunchResult_Deserialize;

export type LaunchResult_Deserialize = {
	launcher: string,
	detail: string,
	warning: string | null,
};

export type LaunchResult_Serialize = {
	launcher: string,
	detail: string,
	warning?: string | null,
};

export type ParameterOption = {
	value: string,
	label: string,
};

export type ScalabilityLimits = {
	groups: { [key in string]: number },
	global_max: number,
	sources: string[],
};

export type ScreenResolution = {
	width: number,
	height: number,
};
