// Generated by landing/scripts/capture-screenshots.mjs.
export const screenshots = {
  ru: {
    preview: [1416, 596],
    restore: [1480, 658],
    diagnostics: [1480, 356],
    "preview-mobile": [716, 800],
    "restore-mobile": [780, 836],
    "diagnostics-mobile": [780, 526],
  },
  en: {
    preview: [1416, 596],
    restore: [1480, 658],
    diagnostics: [1480, 356],
    "preview-mobile": [716, 800],
    "restore-mobile": [780, 836],
    "diagnostics-mobile": [780, 440],
  },
} as const;
