; GSM universal preset — Clarity
Techniques=Clarity,AdaptiveSharpen
TechniqueSorting=Clarity@Clarity,AdaptiveSharpen@Adaptive Sharpen

[Clarity.fx]
ClarityRadius=2
ClarityOffset=2.000000
ClarityBlendIfDark=50
ClarityBlendIfLight=205
ClarityViewBlendIfMask=0
ClarityMaskContrast=0.000000
ClarityMaskIntensity=0.500000

[AdaptiveSharpen.fx]
curveslope=0.500000
curve_height=1.000000
sharp_strength=0.450000
scale_lim=0.100000
scale_cs=0.050000
