; GSM universal preset — Performance
; Лёгкая резкость, без тяжёлых пост-эффектов.
Techniques=AdaptiveSharpen
TechniqueSorting=AdaptiveSharpen@Adaptive Sharpen

[AdaptiveSharpen.fx]
curveslope=0.500000
curve_height=1.000000
sharp_strength=0.650000
scale_lim=0.100000
scale_cs=0.050000
