"""Hand-authored tier A entries for r.Lumen.* (batch 6)."""

LUMEN: dict[str, dict] = {
    "r.Lumen.Reflections.DownsampleFactor": {
        "title": "Lumen отражения: downsample",
        "title_en": "Lumen reflections downsample",
        "description": "Делитель разрешения для Lumen reflections. 1 — полное разрешение, чётче отражения. 2+ — быстрее, но «мыльнее» отражения на воде и металле.",
        "description_en": "Resolution divisor for Lumen reflections. 1 — full res, sharper reflections. 2+ — faster but blurrier on water and metal.",
        "impact": "Средняя–высокая при активных Lumen reflections.",
        "impact_en": "Medium–high with Lumen reflections on.",
        "min": "1", "max": "4", "value_hint": "2 — баланс", "value_hint_en": "2 — balance",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.Reflections.MaxRoughnessToTraceForFoliage": {
        "title": "Lumen: roughness листвы в отражениях",
        "title_en": "Lumen foliage reflection roughness",
        "description": "Максимальная шероховатость листвы, для которой Lumen трассирует отражения. Ниже — меньше листвы в отражениях, выше FPS. Выше — реалистичнее лес у воды.",
        "description_en": "Max foliage roughness Lumen traces for reflections. Lower — less foliage in reflections, more FPS. Higher — more realistic forest by water.",
        "impact": "Средняя в лесах с Lumen reflections.",
        "impact_en": "Medium in forests with Lumen reflections.",
        "min": "0", "max": "1", "value_hint": "0.2–0.4", "value_hint_en": "0.2–0.4",
        "category": "Rendering", "value_type": "float",
    },
    "r.Lumen.Reflections.ScreenSpaceReconstruction.MinWeight": {
        "title": "Lumen SSR: мин. вес реконструкции",
        "title_en": "Lumen SSR reconstruction min weight",
        "description": "Минимальный вес screen-space реконструкции в Lumen reflections. Ниже — больше шума на краях экрана. Выше — стабильнее, но может «залипать» артефакты.",
        "description_en": "Minimum screen-space reconstruction weight in Lumen reflections. Lower — more edge noise. Higher — stabler but may stick artifacts.",
        "impact": "Средняя нагрузка.",
        "impact_en": "Medium load.",
        "min": "0", "max": "1", "value_hint": "не трогать без артефактов", "value_hint_en": "leave unless artifacts",
        "category": "Rendering", "value_type": "float",
    },
    "r.Lumen.Reflections.ScreenSpaceReconstruction.NumSamples": {
        "title": "Lumen SSR: число сэмплов",
        "title_en": "Lumen SSR reconstruction samples",
        "description": "Сколько сэмплов использует screen-space реконструкция Lumen reflections. Больше — чище отражения, тяжелее GPU.",
        "description_en": "Samples for Lumen reflection screen-space reconstruction. More — cleaner reflections, heavier GPU.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "1", "max": "16", "value_hint": "4–8 — баланс", "value_hint_en": "4–8 — balance",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.Reflections.ScreenSpaceReconstruction.TonemapStrength": {
        "title": "Lumen SSR: сила tonemap",
        "title_en": "Lumen SSR tonemap strength",
        "description": "Сила tonemap при смешивании screen-space и traced отражений. Влияет на контраст ярких отражений. Экспертный параметр.",
        "description_en": "Tonemap strength when blending screen-space and traced reflections. Affects bright reflection contrast. Expert parameter.",
        "impact": "Косметика отражений.",
        "impact_en": "Reflection cosmetics.",
        "min": "0", "max": "4", "value_hint": "экспертный", "value_hint_en": "expert only",
        "category": "Rendering", "value_type": "float",
    },
    "r.Lumen.ScreenProbeGather.DownsampleFactor": {
        "title": "Lumen GI: downsample screen probes",
        "title_en": "Lumen GI screen probe downsample",
        "description": "Делитель разрешения screen probe gather — ядро Lumen GI. 1 — максимум качества непрямого света. 2+ — заметная экономия FPS, больше шума в тени.",
        "description_en": "Screen probe gather resolution divisor — Lumen GI core. 1 — max indirect light quality. 2+ — noticeable FPS savings, more shadow noise.",
        "impact": "Очень высокая — главный рычаг Lumen GI.",
        "impact_en": "Very high — main Lumen GI lever.",
        "min": "1", "max": "4", "value_hint": "2 — FPS, 1 — качество", "value_hint_en": "2 — FPS, 1 — quality",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.FullResolutionJitterWidth": {
        "title": "Lumen GI: jitter на full res",
        "title_en": "Lumen GI full-res jitter width",
        "description": "Ширина jitter для screen probes на полном разрешении. Больше — меньше banding, больше мерцания. Меньше — стабильнее, но полосы в GI.",
        "description_en": "Jitter width for full-res screen probes. Wider — less banding, more flicker. Narrower — stabler but GI banding.",
        "impact": "Средняя.",
        "impact_en": "Medium.",
        "min": "0", "max": "4", "value_hint": "по умолчанию", "value_hint_en": "default",
        "category": "Rendering", "value_type": "float",
    },
    "r.Lumen.ScreenProbeGather.IrradianceFormat": {
        "title": "Lumen GI: формат irradiance",
        "title_en": "Lumen GI irradiance format",
        "description": "Формат хранения irradiance в screen probes (технический). Меняет точность цвета GI vs память. Только для экспертов.",
        "description_en": "Irradiance storage format in screen probes (technical). Trades GI color precision vs memory. Experts only.",
        "impact": "Низкая–средняя.",
        "impact_en": "Low–medium.",
        "min": "0", "max": "2", "value_hint": "не менять", "value_hint_en": "don't change",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.MaxRoughnessToEvaluateRoughSpecularForFoliage": {
        "title": "Lumen GI: specular листвы",
        "title_en": "Lumen GI foliage rough specular",
        "description": "До какой roughness считается грубый specular листвы в Lumen GI. Влияет на блики на листьях в тени.",
        "description_en": "Max roughness for rough foliage specular in Lumen GI. Affects leaf highlights in shadow.",
        "impact": "Средняя в лесах.",
        "impact_en": "Medium in forests.",
        "min": "0", "max": "1", "value_hint": "0.3–0.5", "value_hint_en": "0.3–0.5",
        "category": "Rendering", "value_type": "float",
    },
    "r.Lumen.ScreenProbeGather.NumAdaptiveProbes": {
        "title": "Lumen GI: адаптивные probes",
        "title_en": "Lumen GI adaptive probes",
        "description": "Число адаптивных screen probes на пиксель/тайл. Больше — точнее GI в сложных углах, тяжелее GPU.",
        "description_en": "Adaptive screen probes per pixel/tile. More — finer GI in complex corners, heavier GPU.",
        "impact": "Высокая.",
        "impact_en": "High.",
        "min": "0", "max": "16", "value_hint": "не завышать", "value_hint_en": "don't max out",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.RadianceCache.NumProbesToTraceBudget": {
        "title": "Lumen radiance cache: бюджет лучей",
        "title_en": "Lumen radiance cache trace budget",
        "description": "Сколько probes radiance cache трассирует за кадр. Больше — быстрее сходится GI, выше нагрузка.",
        "description_en": "Probes radiance cache traces per frame. More — faster GI convergence, higher load.",
        "impact": "Высокая.",
        "impact_en": "High.",
        "min": "1", "max": "256", "value_hint": "по умолчанию", "value_hint_en": "default",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution": {
        "title": "Lumen radiance cache: разрешение probe",
        "title_en": "Lumen radiance cache probe resolution",
        "description": "Разрешение одного probe в radiance cache. Выше — чище GI, больше VRAM и GPU.",
        "description_en": "Single radiance cache probe resolution. Higher — cleaner GI, more VRAM and GPU.",
        "impact": "Высокая.",
        "impact_en": "High.",
        "min": "4", "max": "32", "value_hint": "16 — баланс", "value_hint_en": "16 — balance",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.ScreenSpaceBentNormal": {
        "title": "Lumen GI: screen-space bent normal",
        "title_en": "Lumen GI screen-space bent normal",
        "description": "0 — без bent normal в screen probes. 1 — вкл: лучше контактные тени и AO в Lumen GI, чуть тяжелее.",
        "description_en": "0 — no bent normals in screen probes. 1 — on: better contact shadows and AO in Lumen GI, slightly heavier.",
        "impact": "Средняя.",
        "impact_en": "Medium.",
        "min": "0", "max": "1", "value_hint": "1 — качество", "value_hint_en": "1 — quality",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.ScreenTraces.HZBTraversal.FullResDepth": {
        "title": "Lumen GI: HZB full-res depth",
        "title_en": "Lumen GI HZB full-res depth",
        "description": "0 — HZB traversal на пониженном depth. 1 — full-res depth для screen traces: точнее GI за углами, дороже.",
        "description_en": "0 — HZB traversal on lower-res depth. 1 — full-res depth for screen traces: more accurate corner GI, costlier.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "0", "max": "1", "value_hint": "0 — FPS", "value_hint_en": "0 — FPS",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.ShortRangeAO.BentNormal": {
        "title": "Lumen short-range AO: bent normal",
        "title_en": "Lumen short-range AO bent normal",
        "description": "0 — short-range AO без bent normal. 1 — вкл: глубже контактное затенение в Lumen, небольшая доп. нагрузка.",
        "description_en": "0 — short-range AO without bent normal. 1 — on: deeper contact shading in Lumen, small extra cost.",
        "impact": "Средняя.",
        "impact_en": "Medium.",
        "min": "0", "max": "1", "value_hint": "1 — детальнее AO", "value_hint_en": "1 — finer AO",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.ShortRangeAO.HardwareRayTracing": {
        "title": "Lumen short-range AO: hardware RT",
        "title_en": "Lumen short-range AO hardware RT",
        "description": "0 — short-range AO без RT-ядер. 1 — hardware RT для AO: точнее углы, нужен RTX/RDNA2+.",
        "description_en": "0 — short-range AO without RT cores. 1 — hardware RT for AO: sharper corners, needs RTX/RDNA2+.",
        "impact": "Очень высокая при 1.",
        "impact_en": "Very high at 1.",
        "min": "0", "max": "1", "value_hint": "0 — без RT", "value_hint_en": "0 — no RT",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.ShortRangeAO.HorizonSearch.ForegroundSampleRejectPower": {
        "title": "Lumen AO: отсечение переднего плана",
        "title_en": "Lumen AO foreground reject power",
        "description": "Степень отсечения foreground сэмплов в horizon search AO. Выше — меньше «ореолов» на объектах перед камерой.",
        "description_en": "Foreground sample reject power in horizon search AO. Higher — fewer halos on foreground objects.",
        "impact": "Косметика AO.",
        "impact_en": "AO cosmetics.",
        "min": "0", "max": "8", "value_hint": "экспертный", "value_hint_en": "expert",
        "category": "Rendering", "value_type": "float",
    },
    "r.Lumen.ScreenProbeGather.ShortRangeAO.HorizonSearch.HZB": {
        "title": "Lumen AO: HZB horizon search",
        "title_en": "Lumen AO HZB horizon search",
        "description": "0 — horizon search без HZB. 1 — HZB ускоряет short-range AO, чуть точнее на сложной геометрии.",
        "description_en": "0 — horizon search without HZB. 1 — HZB speeds short-range AO, slightly better on complex geo.",
        "impact": "Средняя.",
        "impact_en": "Medium.",
        "min": "0", "max": "1", "value_hint": "1 — обычно OK", "value_hint_en": "1 — usually OK",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.StochasticInterpolation": {
        "title": "Lumen GI: стохастическая интерполяция",
        "title_en": "Lumen GI stochastic interpolation",
        "description": "0 — классическая интерполяция probes. 1 — стохастическая: меньше banding, возможно больше шума в движении.",
        "description_en": "0 — classic probe interpolation. 1 — stochastic: less banding, possibly more motion noise.",
        "impact": "Средняя.",
        "impact_en": "Medium.",
        "min": "0", "max": "1", "value_hint": "по вкусу", "value_hint_en": "preference",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.TracingOctahedronResolution": {
        "title": "Lumen GI: разрешение octahedron trace",
        "title_en": "Lumen GI tracing octahedron resolution",
        "description": "Разрешение octahedron map для трассировки из screen probes. Выше — точнее направление GI, тяжелее.",
        "description_en": "Octahedron map resolution for screen probe tracing. Higher — more accurate GI direction, heavier.",
        "impact": "Высокая.",
        "impact_en": "High.",
        "min": "4", "max": "16", "value_hint": "8 — баланс", "value_hint_en": "8 — balance",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.ScreenProbeGather.TwoSidedFoliageBackfaceDiffuse": {
        "title": "Lumen GI: двусторонняя листва",
        "title_en": "Lumen GI two-sided foliage backface",
        "description": "0 — упрощённый diffuse с обратной стороны листвы. 1 — полный backface diffuse: реалистичнее просвечивание листьев.",
        "description_en": "0 — simplified foliage backface diffuse. 1 — full backface: more realistic leaf translucency.",
        "impact": "Средняя в лесах.",
        "impact_en": "Medium in forests.",
        "min": "0", "max": "1", "value_hint": "1 — леса", "value_hint_en": "1 — forests",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TraceMeshSDFs.Allow": {
        "title": "Lumen: трассировка mesh SDF",
        "title_en": "Lumen mesh SDF tracing allow",
        "description": "0 — Lumen не использует mesh distance fields. 1 — вкл SDF tracing: точнее GI/reflections на сложных мешах, выше нагрузка.",
        "description_en": "0 — Lumen skips mesh distance fields. 1 — SDF tracing on: finer GI/reflections on complex meshes, higher load.",
        "impact": "Высокая при 1.",
        "impact_en": "High at 1.",
        "min": "0", "max": "1", "value_hint": "1 — UE5 open world", "value_hint_en": "1 — UE5 open world",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyReflections.FrontLayer.Allow": {
        "title": "Lumen: отражения translucency front layer",
        "title_en": "Lumen translucency front-layer reflections",
        "description": "0 — без отражений на переднем слое прозрачности. 1 — Lumen reflections на стекле/воде в front layer — красивее, тяжелее.",
        "description_en": "0 — no front-layer translucency reflections. 1 — Lumen reflections on glass/water front layer — prettier, heavier.",
        "impact": "Высокая на сценах со стеклом.",
        "impact_en": "High on glass-heavy scenes.",
        "min": "0", "max": "1", "value_hint": "0 — FPS", "value_hint_en": "0 — FPS",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyReflections.FrontLayer.Enable": {
        "title": "Lumen: вкл front layer reflections",
        "title_en": "Lumen translucency front layer enable",
        "description": "Включает проход front-layer reflections для прозрачных материалов в Lumen. Дублирует Allow в части версий UE — держите согласованно.",
        "description_en": "Enables front-layer reflection pass for translucent materials in Lumen. Overlaps Allow on some UE versions — keep consistent.",
        "impact": "Высокая.",
        "impact_en": "High.",
        "min": "0", "max": "1", "value_hint": "как Allow", "value_hint_en": "match Allow",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyVolume.GridPixelSize": {
        "title": "Lumen translucency volume: размер сетки",
        "title_en": "Lumen translucency volume grid pixel size",
        "description": "Размер вокселя translucency lighting volume в пикселях экрана. Больше — грубее свет через дым/стекло, быстрее. Меньше — точнее, тяжелее.",
        "description_en": "Translucency lighting volume voxel size in screen pixels. Larger — coarser light through fog/glass, faster. Smaller — finer, heavier.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "4", "max": "64", "value_hint": "увеличить для FPS", "value_hint_en": "raise for FPS",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyVolume.RadianceCache.NumProbesToTraceBudget": {
        "title": "Lumen translucency: бюджет cache",
        "title_en": "Lumen translucency radiance cache budget",
        "description": "Бюджет трассировки radiance cache для translucency volume. Больше — стабильнее свет в прозрачности.",
        "description_en": "Radiance cache trace budget for translucency volume. More — stabler light in translucency.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "1", "max": "256", "value_hint": "по умолчанию", "value_hint_en": "default",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyVolume.RadianceCache.ProbeResolution": {
        "title": "Lumen translucency: разрешение probe",
        "title_en": "Lumen translucency radiance cache probe resolution",
        "description": "Разрешение probe в translucency radiance cache. Выше — чище просвечивание, больше VRAM.",
        "description_en": "Probe resolution in translucency radiance cache. Higher — cleaner translucency lighting, more VRAM.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "4", "max": "32", "value_hint": "16 — баланс", "value_hint_en": "16 — balance",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyVolume.TraceFromVolume": {
        "title": "Lumen translucency: trace from volume",
        "title_en": "Lumen translucency trace from volume",
        "description": "0 — упрощённый свет для translucency. 1 — трассировка из volume: реалистичнее дым и стекло, тяжелее.",
        "description_en": "0 — simplified translucency lighting. 1 — trace from volume: more realistic smoke and glass, heavier.",
        "impact": "Высокая при 1.",
        "impact_en": "High at 1.",
        "min": "0", "max": "1", "value_hint": "0 — FPS", "value_hint_en": "0 — FPS",
        "category": "Rendering", "value_type": "int",
    },
    "r.Lumen.TranslucencyVolume.TracingOctahedronResolution": {
        "title": "Lumen translucency: octahedron resolution",
        "title_en": "Lumen translucency tracing octahedron resolution",
        "description": "Разрешение octahedron для трассировки в translucency volume. Аналог GI octahedron — влияет на деталь света в прозрачности.",
        "description_en": "Octahedron resolution for translucency volume tracing. Like GI octahedron — affects translucency light detail.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "4", "max": "16", "value_hint": "8 — баланс", "value_hint_en": "8 — balance",
        "category": "Rendering", "value_type": "int",
    },
}
