"""Hand-authored tier A misc entries for expansion v6."""

from __future__ import annotations

# All 166 keys from v6 misc batch (build_misc must return non-None for each).
REQUIRED_KEYS: frozenset[str] = frozenset({
    "r.AmbientOcclusionMaxQuality", "r.AmbientOcclusionMipLevelFactor", "r.AnisotropicMaterials",
    "r.AOQuality", "r.Bloom.ScreenPercentage", "r.CapsuleShadows", "r.CSM.MaxCascades",
    "r.CSM.TransitionScale", "r.CustomDepth", "r.CustomDepthTemporalAAJitter",
    "r.D3D12.ExecuteContextInParallel", "r.D3D12.UseAllowTearing",
    "r.DefaultFeature.AmbientOcclusion", "r.DefaultFeature.AntiAliasing", "r.DefaultFeature.DepthOfField",
    "r.DetectAndWarnOfBadDrivers", "r.DFShadowQuality", "r.DiffuseIndirect.Allow", "r.DisableDistortion",
    "r.DOF.Kernel.MaxBackgroundRadius", "r.DOF.Kernel.MaxForegroundRadius",
    "r.DynamicGlobalIlluminationMethod", "r.EarlyZPass", "r.EarlyZPassOnlyMaterialMasking",
    "r.EmitterSpawnRateScale", "r.FastBlurThreshold", "r.Filter.SizeScale", "r.Fog", "r.Fog.CutoffDistance",
    "r.Fog.Density", "r.Fog.HeightFalloff", "r.Fog.HZBAsyncCompute", "r.Fog.InscatteringColor",
    "r.Fog.StartDistance", "r.FogDensity", "r.FogHeightFalloff", "r.Foliage.DitheredLOD",
    "r.Foliage.GrassCullDistanceScale", "r.Foliage.GrassDensity", "r.Foliage.Wind", "r.ForwardShading",
    "r.GBufferFormat", "r.GlobalIllumination.Denoiser", "r.GPUCrashDebugging",
    "r.HairStrands.Interpolation.UseSingleGuide", "r.HairStrands.SkyAO.SampleCount",
    "r.HairStrands.SkyLighting.IntegrationType", "r.HairStrands.Visibility.MSAA.SamplePerPixel",
    "r.HeterogeneousVolumes", "r.HeterogeneousVolumes.DownsampleFactor", "r.HeterogeneousVolumes.MaxStepCount",
    "r.HeterogeneousVolumes.Shadows.Precision", "r.HeterogeneousVolumes.Shadows.Resolution",
    "r.HeterogeneousVolumes.UseExistenceMask", "r.IndirectLightingCache",
    "r.Landscape.ComponentScreenSizeToUseSubSections", "r.Landscape.LOD0ScreenSize",
    "r.Landscape.LODDistributionScale", "r.LightFunctionQuality", "r.LightMaxDrawDistanceScale",
    "r.LightShaftOcclusion", "r.LumenScene.DirectLighting.MaxLightsPerTile",
    "r.LumenScene.DirectLighting.UpdateFactor", "r.LumenScene.Radiosity.HemisphereProbeResolution",
    "r.LumenScene.Radiosity.ProbeSpacing", "r.LumenScene.Radiosity.UpdateFactor",
    "r.LumenScene.SurfaceCache.CardCaptureRefreshFraction", "r.MaxQualityMode", "r.MipMapLODBias",
    "r.Mobile.AllowDitheredLODTransition", "r.Mobile.AllowSoftwareOcclusion", "r.Mobile.HDR",
    "r.Mobile.MaxMobileCSMs", "r.Mobile.SupportsGen4TAA", "r.MobileHDR", "r.MotionBlur.Amount",
    "r.MotionBlur.HalfResGather", "r.Particle.GPUSimulation", "r.Particle.Lights", "r.Particle.LODBias",
    "r.ParticleLightQuality", "r.ParticleLODBias", "r.RayTracing.Scene.BuildMode",
    "r.Reflection.CaptureResolution", "r.Reflection.Environment", "r.Reflection.MaxRoughness",
    "r.Reflection.Method", "r.Reflection.ScreenSpace", "r.ReflectionMethod", "r.Reflections.Allow",
    "r.Refraction.OffsetQuality", "r.RenderTargetPoolMin", "r.RHICmdBypass", "r.SceneCaptureDepthPrepass",
    "r.SceneColorFormat", "r.SceneDepthHZBAsyncCompute", "r.ScreenProbeGather.ScreenTraces",
    "r.ScreenSpaceReflectionQuality", "r.ScreenSpaceShadows", "r.SeparateTranslucencyPass",
    "r.Shadow.MaxCSMResolution", "r.Shadow.Virtual.MarkCoarsePagesLocal", "r.Shadow.Virtual.MaxPhysicalPages",
    "r.Shadow.Virtual.ResolutionLodBiasDirectional", "r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving",
    "r.Shadow.Virtual.ResolutionLodBiasLocal", "r.Shadow.Virtual.ResolutionLodBiasLocalMoving",
    "r.Shadow.Virtual.SMRT.RayCountDirectional", "r.Shadow.Virtual.SMRT.RayCountLocal",
    "r.Shadow.Virtual.SMRT.SamplesPerRayDirectional", "r.Shadow.Virtual.SMRT.SamplesPerRayLocal",
    "r.SkeletalMeshLODBias", "r.Sky.Atmosphere", "r.Sky.AtmosphereAsyncCompute", "r.Sky.LightSampleCountScale",
    "r.SkyAtmosphere.AerialPerspectiveLUT.DepthResolution",
    "r.SkyAtmosphere.AerialPerspectiveLUT.SampleCountMaxPerSlice", "r.SkyAtmosphere.FastSkyLUT",
    "r.SkyAtmosphere.FastSkyLUT.SampleCountMax", "r.SkyAtmosphere.FastSkyLUT.SampleCountMin",
    "r.SkyAtmosphere.MultiScatteringLUT.SampleCount", "r.SkyAtmosphere.SampleCountMax",
    "r.SkyAtmosphere.SampleCountMin", "r.SkyAtmosphere.TransmittanceLUT.SampleCount",
    "r.SkyAtmosphere.TransmittanceLUT.UseSmallFormat", "r.SkyAtmosphereAsyncCompute",
    "r.SkyLight.RealTimeReflectionCapture", "r.SkylightIntensityMultiplier", "r.SkyQuality",
    "r.SSR.HalfResSceneColor", "r.SSS.HalfRes", "r.SSS.SampleSet", "r.Streaming.AmortizeCPUToGPUCopy",
    "r.Streaming.Boost", "r.Streaming.MaxEffectiveScreenSize", "r.Streaming.MaxNumTexturesToStreamPerFrame",
    "r.Tonemapper.GrainQuantization", "r.TranslucencyLightingVolumeDim", "r.TranslucencyVolumeBlur",
    "r.TSR.History.R11G11B10", "r.TSR.History.ScreenPercentage", "r.TSR.History.UpdateQuality",
    "r.TSR.RejectionAntiAliasingQuality", "r.TSR.ReprojectionField", "r.TSR.Resurrection",
    "r.TSR.ShadingRejection.Flickering", "r.TSR.Velocity.Extrapolation", "r.VolumetricFog.GridPixelSize",
    "r.VolumetricFog.GridSizeZ", "r.VolumetricFog.HistoryMissSupersampleCount", "r.VT.MaxAnisotropy",
    "s.AsyncLoadingThreadEnabled", "s.EventDrivenLoaderEnabled", "s.FlushStreamingOnExit",
    "s.LevelStreamingActorsUpdateTimeLimit", "s.LevelStreamingComponentsRegistrationGranularity",
    "s.LevelStreamingComponentsUnregistrationGranularity", "s.MaxPackageSummarySize",
    "s.MinBulkDataSizeForAsyncLoading", "s.PriorityAsyncLoadingExtraTime",
    "s.PriorityLevelStreamingActorsUpdateExtraTime", "s.TimeLimitExceededMinTime",
    "s.TimeLimitExceededMultiplier", "s.UnregisterComponentsTimeLimit", "s.UseBackgroundLevelStreaming",
    "s.WarnIfTimeLimitExceeded",
})


def E(
    tr: str,
    te: str,
    dr: str,
    de: str,
    ir: str,
    ie: str,
    **kwargs,
) -> dict:
    return {
        "title": tr,
        "title_en": te,
        "description": dr,
        "description_en": de,
        "impact": ir,
        "impact_en": ie,
        "min": kwargs.get("min", "0"),
        "max": kwargs.get("max", "1"),
        "value_hint": kwargs.get("value_hint", "по умолчанию"),
        "value_hint_en": kwargs.get("value_hint_en", "default"),
        "category": kwargs.get("category", "Rendering"),
        "value_type": kwargs.get("value_type", "int"),
    }


# --- group handlers (hand-authored per key) ---

_GROUP_SHADOW_VIRTUAL: dict[str, dict] = {
    "r.Shadow.Virtual.MarkCoarsePagesLocal": E(
        "VSM: coarse pages локально", "VSM mark coarse pages local",
        "0 — грубые страницы VSM не помечаются отдельно для локальных источников. 1 — вкл: точнее переходы у point/spot теней, чуть больше VRAM.",
        "0 — VSM coarse pages not marked separately for local lights. 1 — on: finer point/spot shadow transitions, slightly more VRAM.",
        "Средняя на сценах с локальным светом.", "Medium on local-light-heavy scenes.",
        max="1", value_hint="1 — качество локальных теней", value_hint_en="1 — local shadow quality",
    ),
    "r.Shadow.Virtual.MaxPhysicalPages": E(
        "VSM: лимит физических страниц", "VSM max physical pages",
        "Сколько физических страниц может занять Virtual Shadow Maps. Меньше — экономия VRAM, но «плывущие» тени вдали. Больше — стабильнее на open world.",
        "How many physical pages Virtual Shadow Maps may use. Lower — VRAM savings but swimming distant shadows. Higher — stabler open world.",
        "VRAM и качество теней вдали.", "VRAM and distant shadow quality.",
        min="512", max="16384", value_hint="не занижать на UE5 open world", value_hint_en="don't lower on UE5 open world",
    ),
    "r.Shadow.Virtual.ResolutionLodBiasDirectional": E(
        "VSM: LOD bias солнца", "VSM directional resolution LOD bias",
        "Смещает LOD разрешения VSM для направленного света (солнце). Выше — чётче тени вдали, тяжелее. Ниже — быстрее, мыльнее на горизонте.",
        "Biases VSM resolution LOD for directional light (sun). Higher — sharper distant shadows, heavier. Lower — faster, blurrier horizon.",
        "Сильно на открытых картах.", "Strong on open maps.",
        min="-3", max="3", value_type="float", value_hint="0 — по умолчанию", value_hint_en="0 — default",
    ),
    "r.Shadow.Virtual.ResolutionLodBiasDirectionalMoving": E(
        "VSM: LOD bias солнца в движении", "VSM directional moving LOD bias",
        "LOD bias VSM для солнца, когда камера или солнце движутся. Помогает убрать мерцание динамических теней — экспертный параметр.",
        "VSM LOD bias for sun when camera or sun moves. Helps reduce dynamic shadow flicker — expert parameter.",
        "Средняя при движении камеры.", "Medium during camera motion.",
        min="-3", max="3", value_type="float", value_hint="только при мерцании", value_hint_en="only if flickering",
    ),
    "r.Shadow.Virtual.ResolutionLodBiasLocal": E(
        "VSM: LOD bias локальных теней", "VSM local resolution LOD bias",
        "LOD bias разрешения VSM для point/spot света. Выше — чётче тени от фонарей, выше нагрузка.",
        "VSM resolution LOD bias for point/spot lights. Higher — sharper lamp shadows, higher load.",
        "Средняя в интерьерах.", "Medium indoors.",
        min="-3", max="3", value_type="float", value_hint="0 — стандарт", value_hint_en="0 — standard",
    ),
    "r.Shadow.Virtual.ResolutionLodBiasLocalMoving": E(
        "VSM: LOD bias локальных в движении", "VSM local moving LOD bias",
        "LOD bias VSM для локального света при движении камеры. Снижает артефакты на движущихся point/spot тенях.",
        "VSM LOD bias for local lights when camera moves. Reduces artifacts on moving point/spot shadows.",
        "Средняя в динамичных сценах.", "Medium in dynamic scenes.",
        min="-3", max="3", value_type="float", value_hint="при артефактах", value_hint_en="if artifacts",
    ),
    "r.Shadow.Virtual.SMRT.RayCountDirectional": E(
        "VSM SMRT: лучи солнца", "VSM SMRT directional ray count",
        "Число лучей Screen-space Ray Traced shadows для направленного света в VSM. Больше — мягче penumbra, тяжелее GPU.",
        "Screen-space ray traced shadow rays for directional light in VSM. More — softer penumbra, heavier GPU.",
        "Высокая на солнечных тенях.", "High on sun shadows.",
        min="1", max="16", value_hint="4–8 — баланс", value_hint_en="4–8 — balance",
    ),
    "r.Shadow.Virtual.SMRT.RayCountLocal": E(
        "VSM SMRT: лучи локальных теней", "VSM SMRT local ray count",
        "Число SMRT-лучей для point/spot теней в VSM. Больше — мягче края, дороже на ночных уровнях с фонарями.",
        "SMRT ray count for point/spot VSM shadows. More — softer edges, costlier on lamp-heavy night levels.",
        "Средняя–высокая в интерьерах.", "Medium–high indoors.",
        min="1", max="16", value_hint="не завышать", value_hint_en="don't max out",
    ),
    "r.Shadow.Virtual.SMRT.SamplesPerRayDirectional": E(
        "VSM SMRT: сэмплы на луч солнца", "VSM SMRT directional samples per ray",
        "Сэмплов на луч SMRT для солнца. Больше — чище мягкие тени, выше нагрузка на GPU.",
        "Samples per SMRT ray for sun. More — cleaner soft shadows, higher GPU load.",
        "Высокая.", "High.",
        min="1", max="16", value_hint="8 — баланс", value_hint_en="8 — balance",
    ),
    "r.Shadow.Virtual.SMRT.SamplesPerRayLocal": E(
        "VSM SMRT: сэмплы на локальный луч", "VSM SMRT local samples per ray",
        "Сэмплов на луч SMRT для локального света. Влияет на качество мягких теней от прожекторов.",
        "Samples per SMRT ray for local lights. Affects soft shadow quality from spotlights.",
        "Средняя–высокая.", "Medium–high.",
        min="1", max="16", value_hint="4–8", value_hint_en="4–8",
    ),
}

_GROUP_TSR: dict[str, dict] = {
    "r.TSR.History.R11G11B10": E(
        "TSR: история R11G11B10", "TSR history R11G11B10",
        "0 — полная precision в history buffer TSR. 1 — R11G11B10: экономия VRAM и bandwidth, возможен чуть больший шум в движении.",
        "0 — full precision TSR history buffer. 1 — R11G11B10: VRAM/bandwidth savings, possibly more motion noise.",
        "Средняя при TSR upscaling.", "Medium with TSR upscaling.",
        value_hint="1 — FPS на слабом GPU", value_hint_en="1 — FPS on weak GPU",
    ),
    "r.TSR.History.ScreenPercentage": E(
        "TSR: разрешение history", "TSR history screen percentage",
        "Процент разрешения буфера истории TSR от экрана. 100 — полное. Ниже — быстрее, но больше ghosting. Выше 100 — sharper, тяжелее.",
        "TSR history buffer resolution percent of screen. 100 — full. Lower — faster but more ghosting. Above 100 — sharper, heavier.",
        "Сильно влияет на резкость TSR.", "Strong TSR sharpness impact.",
        min="50", max="200", value_type="float", value_hint="100 — стандарт", value_hint_en="100 — standard",
    ),
    "r.TSR.History.UpdateQuality": E(
        "TSR: качество обновления history", "TSR history update quality",
        "Насколько агрессивно TSR обновляет temporal history. 0 — стабильнее, больше ghosting. 4 — резче в движении, больше мерцания.",
        "How aggressively TSR updates temporal history. 0 — stabler, more ghosting. 4 — sharper in motion, more flicker.",
        "Средняя нагрузка и артефакты TSR.", "Medium TSR load and artifacts.",
        max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
    ),
    "r.TSR.RejectionAntiAliasingQuality": E(
        "TSR: AA rejection quality", "TSR rejection anti-aliasing quality",
        "Качество anti-aliasing при rejection в TSR — убирает «лестницы» на отвергнутых сэмплах. Выше — чище края, чуть тяжелее.",
        "Anti-aliasing quality during TSR rejection — removes jaggies on rejected samples. Higher — cleaner edges, slightly heavier.",
        "Средняя при TSR.", "Medium with TSR.",
        max="4", value_hint="2–3", value_hint_en="2–3",
    ),
    "r.TSR.ReprojectionField": E(
        "TSR: reprojection field", "TSR reprojection field",
        "0 — классическая reprojection TSR. 1 — reprojection field: лучше на тонких объектах и волосах, но экспериментальнее.",
        "0 — classic TSR reprojection. 1 — reprojection field: better on thin geometry and hair, more experimental.",
        "Средняя, зависит от сцены.", "Medium, scene-dependent.",
        value_hint="1 — тонкая геометрия", value_hint_en="1 — thin geometry",
    ),
    "r.TSR.Resurrection": E(
        "TSR: resurrection", "TSR resurrection",
        "0 — выкл восстановление history после disocclusion. 1 — вкл: меньше «провалов» деталей после резких поворотов камеры, чуть тяжелее.",
        "0 — no history resurrection after disocclusion. 1 — on: fewer detail pops after sharp camera turns, slightly heavier.",
        "Средняя на динамичной камере.", "Medium with dynamic camera.",
        value_hint="1 — UE5.4+ AA quality", value_hint_en="1 — UE5.4+ AA quality",
    ),
    "r.TSR.ShadingRejection.Flickering": E(
        "TSR: подавление мерцания", "TSR shading rejection flickering",
        "Насколько TSR подавляет мерцание specular при rejection. Выше — стабильнее блики, возможно «мыло» на металле.",
        "How much TSR suppresses specular flicker during rejection. Higher — stabler highlights, possible metal blur.",
        "Косметика и стабильность TSR.", "TSR cosmetics and stability.",
        max="4", value_type="float", value_hint="2 — баланс", value_hint_en="2 — balance",
    ),
    "r.TSR.Velocity.Extrapolation": E(
        "TSR: экстраполяция velocity", "TSR velocity extrapolation",
        "0 — без экстраполяции velocity в TSR. 1 — вкл: меньше ghosting на быстрых объектах, риск артефактов на резких поворотах.",
        "0 — no velocity extrapolation in TSR. 1 — on: less ghosting on fast objects, artifact risk on sharp turns.",
        "Средняя при быстром движении.", "Medium during fast motion.",
        value_hint="1 — гонки/экшен", value_hint_en="1 — racing/action",
    ),
}

_GROUP_SKY_ATMOSPHERE: dict[str, dict] = {
    "r.SkyAtmosphere.AerialPerspectiveLUT.DepthResolution": E(
        "Sky Atmosphere: depth aerial LUT", "Sky atmosphere aerial perspective LUT depth resolution",
        "Разрешение depth-оси LUT aerial perspective. Выше — точнее дымка на горизонте, больше VRAM.",
        "Aerial perspective LUT depth resolution. Higher — more accurate horizon haze, more VRAM.",
        "Средняя на open world.", "Medium on open world.",
        min="4", max="256", value_hint="32–64 — баланс", value_hint_en="32–64 — balance",
    ),
    "r.SkyAtmosphere.AerialPerspectiveLUT.SampleCountMaxPerSlice": E(
        "Sky Atmosphere: сэмплы aerial LUT", "Sky atmosphere aerial LUT samples per slice",
        "Макс. сэмплов на slice aerial perspective LUT. Больше — чище атмосферная дымка, тяжелее.",
        "Max samples per aerial perspective LUT slice. More — cleaner atmospheric haze, heavier.",
        "Средняя на открытом небе.", "Medium under open sky.",
        min="1", max="32", value_hint="не завышать", value_hint_en="don't max out",
    ),
    "r.SkyAtmosphere.FastSkyLUT": E(
        "Sky Atmosphere: быстрый sky LUT", "Sky atmosphere fast sky LUT",
        "0 — полный расчёт неба. 1 — ускоренный sky LUT: быстрее на open world, чуть менее точный закат.",
        "0 — full sky evaluation. 1 — fast sky LUT: faster open world, slightly less accurate sunsets.",
        "Средняя на открытых картах.", "Medium on open maps.",
        value_hint="1 — FPS open world", value_hint_en="1 — open-world FPS",
    ),
    "r.SkyAtmosphere.FastSkyLUT.SampleCountMax": E(
        "Sky Atmosphere: max сэмплы fast sky", "Sky atmosphere fast sky LUT max samples",
        "Верхний предел сэмплов fast sky LUT. Больше — плавнее градиент неба, дороже.",
        "Fast sky LUT max sample count. More — smoother sky gradient, costlier.",
        "Средняя.", "Medium.",
        min="1", max="64", value_hint="по умолчанию", value_hint_en="default",
    ),
    "r.SkyAtmosphere.FastSkyLUT.SampleCountMin": E(
        "Sky Atmosphere: min сэмплы fast sky", "Sky atmosphere fast sky LUT min samples",
        "Минимум сэмплов fast sky LUT — нижняя граница качества неба при оптимизациях.",
        "Fast sky LUT minimum samples — lower bound for sky quality during optimizations.",
        "Низкая–средняя.", "Low–medium.",
        min="1", max="32", value_hint="не опускать слишком", value_hint_en="don't drop too low",
    ),
    "r.SkyAtmosphere.MultiScatteringLUT.SampleCount": E(
        "Sky Atmosphere: multi-scattering сэмплы", "Sky atmosphere multi-scattering LUT samples",
        "Сэмплов в LUT множественного рассеяния атмосферы. Больше — реалистичнее закаты и туманность неба.",
        "Multi-scattering atmosphere LUT samples. More — more realistic sunsets and sky glow.",
        "Средняя на открытом небе.", "Medium under open sky.",
        min="1", max="32", value_hint="8–16", value_hint_en="8–16",
    ),
    "r.SkyAtmosphere.SampleCountMax": E(
        "Sky Atmosphere: max сэмплы", "Sky atmosphere max samples",
        "Максимум ray-march сэмплов sky atmosphere. Больше — чище небо и aerial perspective, тяжелее GPU.",
        "Max sky atmosphere ray-march samples. More — cleaner sky and aerial perspective, heavier GPU.",
        "Средняя–высокая.", "Medium–high.",
        min="1", max="64", value_hint="16 — баланс", value_hint_en="16 — balance",
    ),
    "r.SkyAtmosphere.SampleCountMin": E(
        "Sky Atmosphere: min сэмплы", "Sky atmosphere min samples",
        "Минимум сэмплов sky atmosphere — нижний предел качества неба при LOD.",
        "Minimum sky atmosphere samples — lower quality bound for sky LOD.",
        "Низкая–средняя.", "Low–medium.",
        min="1", max="32", value_hint="не ниже дефолта", value_hint_en="not below default",
    ),
    "r.SkyAtmosphere.TransmittanceLUT.SampleCount": E(
        "Sky Atmosphere: transmittance сэмплы", "Sky atmosphere transmittance LUT samples",
        "Сэмплов в transmittance LUT — влияет на точность поглощения света атмосферой.",
        "Transmittance LUT samples — affects atmospheric light absorption accuracy.",
        "Средняя.", "Medium.",
        min="1", max="32", value_hint="10 — стандарт", value_hint_en="10 — standard",
    ),
    "r.SkyAtmosphere.TransmittanceLUT.UseSmallFormat": E(
        "Sky Atmosphere: compact transmittance", "Sky atmosphere transmittance small format",
        "0 — полный формат transmittance LUT. 1 — компактный: меньше VRAM, возможны banding на горизонте.",
        "0 — full transmittance LUT format. 1 — compact: less VRAM, possible horizon banding.",
        "VRAM и качество горизонта.", "VRAM and horizon quality.",
        value_hint="0 — качество", value_hint_en="0 — quality",
    ),
}

_GROUP_FOG: dict[str, dict] = {
    "r.Fog": E(
        "Экспоненциальный туман", "Exponential fog",
        "0 — exponential fog выкл. 1 — вкл классический туман UE: дальность и плотность задаются r.FogDensity и r.FogHeightFalloff.",
        "0 — exponential fog off. 1 — classic UE fog on: density and height use r.FogDensity and r.FogHeightFalloff.",
        "Средняя на туманных уровнях.", "Medium on foggy levels.",
        value_hint="1 — если туман в игре", value_hint_en="1 — if game uses fog",
    ),
    "r.Fog.CutoffDistance": E(
        "Туман: cutoff distance", "Fog cutoff distance",
        "Расстояние, после которого туман полностью скрывает сцену. Меньше — короче видимость, выше FPS на горизонте.",
        "Distance after which fog fully occludes the scene. Lower — shorter visibility, higher horizon FPS.",
        "Средняя на open world.", "Medium on open world.",
        min="1000", max="500000", value_type="float", value_hint="под дизайн уровня", value_hint_en="match level design",
    ),
    "r.Fog.Density": E(
        "Туман: плотность (legacy path)", "Fog density (legacy path)",
        "Плотность exponential fog через r.Fog.* namespace. Выше — гуще туман, короче видимость.",
        "Exponential fog density via r.Fog.* namespace. Higher — denser fog, shorter visibility.",
        "Косметика и дальность.", "Cosmetics and view distance.",
        min="0", max="0.1", value_type="float", value_hint="0.02 — лёгкая дымка", value_hint_en="0.02 — light haze",
    ),
    "r.Fog.HeightFalloff": E(
        "Туман: height falloff (legacy)", "Fog height falloff (legacy)",
        "Как быстро туман рассеивается по высоте в r.Fog.*. Больше — туман «лежит» ниже, меньше — равномернее.",
        "How fast fog fades with height in r.Fog.*. Higher — fog stays lower, lower — more uniform.",
        "Косметика неба и гор.", "Sky and mountain cosmetics.",
        min="0", max="2", value_type="float", value_hint="0.2 — стандарт", value_hint_en="0.2 — standard",
    ),
    "r.Fog.HZBAsyncCompute": E(
        "Туман: HZB async compute", "Fog HZB async compute",
        "0 — HZB для fog на graphics queue. 1 — async compute: может дать FPS на современных GPU, зависит от драйвера.",
        "0 — fog HZB on graphics queue. 1 — async compute: may boost FPS on modern GPUs, driver-dependent.",
        "Зависит от GPU.", "GPU-dependent.",
        value_hint="1 — современный GPU", value_hint_en="1 — modern GPU",
    ),
    "r.Fog.InscatteringColor": E(
        "Туман: цвет inscattering", "Fog inscattering color",
        "Цвет рассеянного света в тумане (RGB множители). Влияет на «синеву» или «жёлтый» туман на закате.",
        "Inscattered light color in fog (RGB multipliers). Affects blue or golden sunset fog tint.",
        "Косметика.", "Cosmetic.",
        min="0", max="4", value_type="float", value_hint="1 — нейтральный", value_hint_en="1 — neutral",
    ),
    "r.Fog.StartDistance": E(
        "Туман: start distance", "Fog start distance",
        "Расстояние от камеры, где туман начинает проявляться. Больше — чище ближний план, туман только вдали.",
        "Distance from camera where fog begins. Higher — clearer foreground, fog only far away.",
        "Косметика дальности.", "View-distance cosmetics.",
        min="0", max="100000", value_type="float", value_hint="0 — с камеры", value_hint_en="0 — from camera",
    ),
    "r.FogDensity": E(
        "Плотность тумана (глоб.)", "Global fog density",
        "Главный множитель плотности exponential fog. 0 — без тумана. Выше — гуще, короче видимость на open world.",
        "Main exponential fog density multiplier. 0 — no fog. Higher — denser, shorter open-world visibility.",
        "Средняя на туманных картах.", "Medium on foggy maps.",
        min="0", max="0.1", value_type="float", value_hint="не трогать без цели", value_hint_en="don't tweak blindly",
    ),
    "r.FogHeightFalloff": E(
        "Height falloff тумана", "Global fog height falloff",
        "Насколько быстро туман спадает с высотой. Больше — низинный туман у земли, меньше — равномерная дымка.",
        "How quickly fog falls off with altitude. Higher — low-lying ground fog, lower — even haze.",
        "Косметика.", "Cosmetic.",
        min="0", max="2", value_type="float", value_hint="0.2 — типично", value_hint_en="0.2 — typical",
    ),
}

_GROUP_STREAMING: dict[str, dict] = {
    "r.Streaming.AmortizeCPUToGPUCopy": E(
        "Streaming: amortize CPU→GPU copy", "Streaming amortize CPU to GPU copy",
        "0 — копирование текстур на GPU сразу. 1 — растянуто по кадрам: меньше фризов, дольше «прогрузка» blur.",
        "0 — immediate GPU texture copy. 1 — spread across frames: fewer hitches, longer blurry pop-in.",
        "CPU и фризы подгрузки.", "CPU and streaming hitches.",
        value_hint="1 — против фризов", value_hint_en="1 — against hitches",
        category="Textures",
    ),
    "r.Streaming.Boost": E(
        "Streaming: boost приоритет", "Streaming priority boost",
        "Множитель приоритета подгрузки текстур. Выше 1 — агрессивнее stream-in (быстрее чёткие текстуры, больше IO/VRAM).",
        "Texture streaming priority multiplier. Above 1 — more aggressive stream-in (sharper textures faster, more IO/VRAM).",
        "VRAM и фризы.", "VRAM and hitches.",
        min="0.1", max="10", value_type="float", value_hint="1 — норма", value_hint_en="1 — normal",
        category="Textures",
    ),
    "r.Streaming.MaxEffectiveScreenSize": E(
        "Streaming: max effective screen size", "Streaming max effective screen size",
        "Ограничивает «эффективное» разрешение для выбора mip текстур. Ниже — экономия VRAM, мыльнее текстуры вдали.",
        "Caps effective resolution for texture mip selection. Lower — VRAM savings, blurrier distant textures.",
        "VRAM и резкость текстур.", "VRAM and texture sharpness.",
        min="0", max="8192", value_hint="не ниже реального res", value_hint_en="not below actual res",
        category="Textures",
    ),
    "r.Streaming.MaxNumTexturesToStreamPerFrame": E(
        "Streaming: текстур за кадр", "Streaming max textures per frame",
        "Сколько текстур может подгрузиться за один кадр. Больше — быстрее резкость после поворота, выше риск фриза.",
        "How many textures may stream per frame. More — faster sharpness after turning, higher hitch risk.",
        "CPU, IO и фризы.", "CPU, IO, and hitches.",
        min="0", max="512", value_hint="8–16 — баланс", value_hint_en="8–16 — balance",
        category="Textures",
    ),
}

_GROUP_STREAMING_SETTINGS: dict[str, dict] = {
    "s.AsyncLoadingThreadEnabled": E(
        "Async loading thread", "Async loading thread",
        "False — загрузка на game thread (фризы). True — отдельный поток async loading: меньше stutter при travel и streaming.",
        "False — load on game thread (hitches). True — dedicated async loading thread: less stutter on travel/streaming.",
        "CPU и фризы загрузки.", "CPU and load hitches.",
        value_type="bool", value_hint="True — UE5 default", value_hint_en="True — UE5 default",
        category="Other",
    ),
    "s.EventDrivenLoaderEnabled": E(
        "Event-driven loader (EDL)", "Event-driven loader",
        "False — классический loader. True — EDL: быстрее загрузка уровней в UE4.27+/UE5, но чувствителен к контенту.",
        "False — classic loader. True — EDL: faster level loads in UE4.27+/UE5, content-sensitive.",
        "Время загрузки и стабильность.", "Load times and stability.",
        value_type="bool", value_hint="True — обычно OK", value_hint_en="True — usually OK",
        category="Other",
    ),
    "s.FlushStreamingOnExit": E(
        "Flush streaming при выходе", "Flush streaming on exit",
        "True — сбрасывает streaming при выходе (чище shutdown). False — быстрее выход, возможны предупреждения в логе.",
        "True — flushes streaming on exit (cleaner shutdown). False — faster exit, possible log warnings.",
        "Только shutdown.", "Shutdown only.",
        value_type="bool", value_hint="True — безопаснее", value_hint_en="True — safer",
        category="Other",
    ),
    "s.LevelStreamingActorsUpdateTimeLimit": E(
        "Streaming: лимит обновления actors", "Level streaming actors update time limit",
        "Макс. миллисекунд за кадр на обновление streamed actors. Меньше — плавнее FPS, медленнее «оживление» уровня.",
        "Max ms per frame for streamed actor updates. Lower — smoother FPS, slower level 'wake-up'.",
        "CPU и фризы streaming.", "CPU and streaming hitches.",
        min="0", max="50", value_type="float", value_hint="5 — типично", value_hint_en="5 — typical",
        category="Other",
    ),
    "s.LevelStreamingComponentsRegistrationGranularity": E(
        "Streaming: granularity регистрации", "Streaming components registration granularity",
        "Сколько компонентов регистрируется за один шаг streaming. Больше — быстрее load-in, риск фриза.",
        "Components registered per streaming step. More — faster load-in, hitch risk.",
        "CPU streaming.", "CPU streaming.",
        min="1", max="10000", value_hint="не завышать", value_hint_en="don't max out",
        category="Other",
    ),
    "s.LevelStreamingComponentsUnregistrationGranularity": E(
        "Streaming: granularity снятия", "Streaming components unregistration granularity",
        "Сколько компонентов снимается за шаг при unload streaming. Аналог registration — баланс FPS vs скорость unload.",
        "Components unregistered per streaming unload step. Like registration — FPS vs unload speed balance.",
        "CPU streaming.", "CPU streaming.",
        min="1", max="10000", value_hint="как registration", value_hint_en="match registration",
        category="Other",
    ),
    "s.MaxPackageSummarySize": E(
        "Streaming: max package summary", "Max package summary size",
        "Макс. размер summary при чтении пакета. Больше — быстрее metadata для больших ассетов, больше RAM на load.",
        "Max summary size when reading packages. Larger — faster metadata for big assets, more load RAM.",
        "RAM и скорость загрузки.", "RAM and load speed.",
        min="1024", max="1048576", value_hint="дефолт UE", value_hint_en="UE default",
        category="Other",
    ),
    "s.MinBulkDataSizeForAsyncLoading": E(
        "Streaming: min bulk для async", "Min bulk data size for async loading",
        "Минимальный размер bulk data для async пути. Меньше — больше мелких async read, выше overhead.",
        "Minimum bulk data size for async path. Lower — more small async reads, higher overhead.",
        "IO и загрузка.", "IO and loading.",
        min="0", max="1048576", value_hint="не трогать", value_hint_en="leave alone",
        category="Other",
    ),
    "s.PriorityAsyncLoadingExtraTime": E(
        "Streaming: extra time async load", "Priority async loading extra time",
        "Доп. миллисекунды на приоритетную async загрузку за кадр. Больше — быстрее critical loads, риск фриза.",
        "Extra ms per frame for priority async loading. More — faster critical loads, hitch risk.",
        "CPU и load hitches.", "CPU and load hitches.",
        min="0", max="100", value_type="float", value_hint="экспертный", value_hint_en="expert",
        category="Other",
    ),
    "s.PriorityLevelStreamingActorsUpdateExtraTime": E(
        "Streaming: extra time actors update", "Priority level streaming actors update extra time",
        "Доп. время на обновление приоритетных streamed actors. Ускоряет «важные» акторы при входе в sublevel.",
        "Extra time for priority streamed actor updates. Speeds 'important' actors entering sublevel.",
        "CPU streaming.", "CPU streaming.",
        min="0", max="100", value_type="float", value_hint="при медленном streaming", value_hint_en="if slow streaming",
        category="Other",
    ),
    "s.TimeLimitExceededMinTime": E(
        "Streaming: min time limit exceeded", "Time limit exceeded min time",
        "Минимальное время, после которого streaming считает кадр «перегруженным». Технический таймер бюджета.",
        "Minimum time before streaming marks frame as overloaded. Technical budget timer.",
        "CPU tuning.", "CPU tuning.",
        min="0", max="100", value_type="float", value_hint="экспертный", value_hint_en="expert",
        category="Other",
    ),
    "s.TimeLimitExceededMultiplier": E(
        "Streaming: multiplier time limit", "Time limit exceeded multiplier",
        "Множитель порога превышения бюджета streaming. Выше — реже aggressive cut, возможны фризы.",
        "Streaming budget exceed threshold multiplier. Higher — less aggressive cuts, possible hitches.",
        "CPU streaming.", "CPU streaming.",
        min="1", max="10", value_type="float", value_hint="не трогать", value_hint_en="leave alone",
        category="Other",
    ),
    "s.UnregisterComponentsTimeLimit": E(
        "Streaming: лимит unregister", "Unregister components time limit",
        "Макс. ms за кадр на unregister компонентов при streaming unload. Баланс плавности vs скорость выгрузки.",
        "Max ms per frame unregistering components on streaming unload. Smoothness vs unload speed.",
        "CPU streaming.", "CPU streaming.",
        min="0", max="50", value_type="float", value_hint="5 — типично", value_hint_en="5 — typical",
        category="Other",
    ),
    "s.UseBackgroundLevelStreaming": E(
        "Background level streaming", "Background level streaming",
        "False — streaming на foreground. True — фоновый поток: меньше hitches при open world, сложнее отладка.",
        "False — foreground streaming. True — background thread: fewer open-world hitches, harder to debug.",
        "CPU и open world.", "CPU and open world.",
        value_type="bool", value_hint="True — большие миры", value_hint_en="True — large worlds",
        category="Other",
    ),
    "s.WarnIfTimeLimitExceeded": E(
        "Streaming: warn time limit", "Warn if time limit exceeded",
        "True — предупреждения в лог при превышении streaming budget (полезно для отладки фризов).",
        "True — log warnings when streaming budget exceeded (useful for debugging hitches).",
        "Только отладка.", "Debug only.",
        value_type="bool", value_hint="True при tuning", value_hint_en="True when tuning",
        category="Other",
    ),
}

_GROUP_LUMEN_SCENE: dict[str, dict] = {
    "r.LumenScene.DirectLighting.MaxLightsPerTile": E(
        "Lumen scene: max lights per tile", "Lumen scene max lights per tile",
        "Сколько источников света учитывается на тайл в Lumen direct lighting. Больше — точнее освещение в клубах с фонарями, тяжелее.",
        "Lights evaluated per tile in Lumen direct lighting. More — finer lighting in lamp-heavy scenes, heavier.",
        "Высокая на ночных уровнях.", "High on night levels.",
        min="1", max="32", value_hint="не завышать", value_hint_en="don't max out",
    ),
    "r.LumenScene.DirectLighting.UpdateFactor": E(
        "Lumen scene: update direct lighting", "Lumen scene direct lighting update factor",
        "Как часто обновляется direct lighting в Lumen scene. Выше — быстрее реакция на движущийся свет, больше мерцания и нагрузки.",
        "How often Lumen scene direct lighting updates. Higher — faster moving-light response, more flicker and load.",
        "Средняя–высокая.", "Medium–high.",
        min="0.1", max="4", value_type="float", value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.LumenScene.Radiosity.HemisphereProbeResolution": E(
        "Lumen radiosity: разрешение probe", "Lumen radiosity hemisphere probe resolution",
        "Разрешение hemisphere probe в Lumen radiosity. Выше — чище indirect bounce в scene, больше VRAM.",
        "Hemisphere probe resolution in Lumen radiosity. Higher — cleaner scene indirect bounce, more VRAM.",
        "Высокая.", "High.",
        min="4", max="32", value_hint="16 — баланс", value_hint_en="16 — balance",
    ),
    "r.LumenScene.Radiosity.ProbeSpacing": E(
        "Lumen radiosity: spacing probes", "Lumen radiosity probe spacing",
        "Расстояние между radiosity probes в Lumen scene. Больше — быстрее, грубее GI. Меньше — детальнее, тяжелее.",
        "Spacing between Lumen scene radiosity probes. Larger — faster, coarser GI. Smaller — finer, heavier.",
        "Очень высокая.", "Very high.",
        min="50", max="2000", value_type="float", value_hint="не уменьшать без RT", value_hint_en="don't shrink without reason",
    ),
    "r.LumenScene.Radiosity.UpdateFactor": E(
        "Lumen radiosity: update factor", "Lumen radiosity update factor",
        "Скорость обновления radiosity в Lumen scene. Выше — быстрее смена GI при динамическом свете, больше шума.",
        "Lumen scene radiosity update rate. Higher — faster GI changes with dynamic light, more noise.",
        "Высокая.", "High.",
        min="0.1", max="4", value_type="float", value_hint="1 — баланс", value_hint_en="1 — balance",
    ),
    "r.LumenScene.SurfaceCache.CardCaptureRefreshFraction": E(
        "Lumen surface cache: refresh cards", "Lumen surface cache card capture refresh fraction",
        "Доля surface cache cards, перезахватываемых за кадр. Выше — свежее GI на движущихся объектах, тяжелее GPU.",
        "Fraction of surface cache cards recaptured per frame. Higher — fresher GI on moving objects, heavier GPU.",
        "Очень высокая.", "Very high.",
        min="0.01", max="1", value_type="float", value_hint="0.1 — типично", value_hint_en="0.1 — typical",
    ),
}

_GROUP_HETEROGENEOUS_VOLUMES: dict[str, dict] = {
    "r.HeterogeneousVolumes": E(
        "Heterogeneous volumes", "Heterogeneous volumes",
        "0 — volumetric media (облака дыма, FX) через heterogeneous volumes выкл. 1 — вкл: реалистичный volumetric rendering, очень тяжело.",
        "0 — heterogeneous volumetric media off. 1 — on: realistic volumetric rendering, very heavy.",
        "Очень высокая при 1.", "Very high at 1.",
        value_hint="0 — FPS", value_hint_en="0 — FPS",
    ),
    "r.HeterogeneousVolumes.DownsampleFactor": E(
        "Hetero volumes: downsample", "Heterogeneous volumes downsample",
        "Делитель разрешения heterogeneous volumes. 1 — full res дым/огонь. 2+ — быстрее, blockier volumetric FX.",
        "Heterogeneous volumes resolution divisor. 1 — full-res smoke/fire. 2+ — faster, blockier volumetric FX.",
        "Очень высокая.", "Very high.",
        min="1", max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
    ),
    "r.HeterogeneousVolumes.MaxStepCount": E(
        "Hetero volumes: max steps", "Heterogeneous volumes max step count",
        "Макс. шагов ray march через heterogeneous volume. Больше — плотнее дым без дыр, тяжелее GPU.",
        "Max ray-march steps through heterogeneous volume. More — denser smoke without holes, heavier GPU.",
        "Очень высокая.", "Very high.",
        min="8", max="256", value_hint="64 — баланс", value_hint_en="64 — balance",
    ),
    "r.HeterogeneousVolumes.Shadows.Precision": E(
        "Hetero volumes: точность теней", "Heterogeneous volumes shadow precision",
        "Точность теней от heterogeneous volumes. Выше — чётче self-shadowing дыма, дороже.",
        "Shadow precision for heterogeneous volumes. Higher — sharper volumetric self-shadowing, costlier.",
        "Высокая.", "High.",
        min="0", max="2", value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.HeterogeneousVolumes.Shadows.Resolution": E(
        "Hetero volumes: разрешение теней", "Heterogeneous volumes shadow resolution",
        "Разрешение shadow map для heterogeneous volumes. Ниже — FPS, грубее тени в дыме.",
        "Shadow map resolution for heterogeneous volumes. Lower — FPS, coarser smoke shadows.",
        "Высокая.", "High.",
        min="128", max="2048", value_hint="512 — баланс", value_hint_en="512 — balance",
    ),
    "r.HeterogeneousVolumes.UseExistenceMask": E(
        "Hetero volumes: existence mask", "Heterogeneous volumes existence mask",
        "0 — без existence mask оптимизации. 1 — вкл: пропуск пустых voxels, быстрее на разреженном дыме.",
        "0 — no existence mask optimization. 1 — on: skips empty voxels, faster on sparse smoke.",
        "Средняя–высокая.", "Medium–high.",
        value_hint="1 — обычно OK", value_hint_en="1 — usually OK",
    ),
}

_GROUP_HAIR_STRANDS: dict[str, dict] = {
    "r.HairStrands.Interpolation.UseSingleGuide": E(
        "Hair: single guide interpolation", "Hair strands single guide interpolation",
        "0 — несколько guide strands для интерполяции. 1 — один guide: быстрее, но грубее прически на движении.",
        "0 — multiple guide strands for interpolation. 1 — single guide: faster but coarser hair motion.",
        "Средняя на персонажах с hair groom.", "Medium on hair-groom characters.",
        value_hint="0 — качество волос", value_hint_en="0 — hair quality",
    ),
    "r.HairStrands.SkyAO.SampleCount": E(
        "Hair: sky AO samples", "Hair strands sky AO sample count",
        "Сэмплов sky ambient occlusion для groom hair. Больше — глубже затенение волос на открытом небе.",
        "Sky AO samples for groom hair. More — deeper hair shading under open sky.",
        "Средняя на close-up персонажей.", "Medium on close-up characters.",
        min="1", max="16", value_hint="4 — баланс", value_hint_en="4 — balance",
    ),
    "r.HairStrands.SkyLighting.IntegrationType": E(
        "Hair: sky lighting integration", "Hair strands sky lighting integration type",
        "Метод интеграции небесного освещения в hair strands (0–2). Влияет на блики и цвет волос на солнце.",
        "Sky lighting integration method for hair strands (0–2). Affects sun highlights and hair color.",
        "Средняя.", "Medium.",
        max="2", value_hint="не менять без groom", value_hint_en="don't change without groom",
    ),
    "r.HairStrands.Visibility.MSAA.SamplePerPixel": E(
        "Hair: MSAA samples per pixel", "Hair strands visibility MSAA samples per pixel",
        "MSAA сэмплов на пиксель для visibility hair strands. Больше — меньше aliasing волос, тяжелее.",
        "MSAA samples per pixel for hair strand visibility. More — less hair aliasing, heavier.",
        "Средняя–высокая.", "Medium–high.",
        min="1", max="8", value_hint="2–4", value_hint_en="2–4",
    ),
}

_GROUP_MOBILE: dict[str, dict] = {
    "r.Mobile.AllowDitheredLODTransition": E(
        "Mobile: dithered LOD transition", "Mobile dithered LOD transition",
        "0 — резкий pop LOD на mobile. 1 — dithered переход: плавнее, но возможен шум на краях объектов.",
        "0 — hard LOD pop on mobile. 1 — dithered transition: smoother but possible edge noise.",
        "Низкая–средняя на mobile.", "Low–medium on mobile.",
        value_hint="1 — плавнее LOD", value_hint_en="1 — smoother LOD",
    ),
    "r.Mobile.AllowSoftwareOcclusion": E(
        "Mobile: software occlusion", "Mobile software occlusion",
        "0 — без CPU occlusion culling на mobile. 1 — software occlusion: FPS на плотных сценах, риск пропуска объектов.",
        "0 — no CPU occlusion culling on mobile. 1 — software occlusion: FPS on dense scenes, object pop-in risk.",
        "CPU и видимость.", "CPU and visibility.",
        value_hint="1 — плотные уровни", value_hint_en="1 — dense levels",
    ),
    "r.Mobile.HDR": E(
        "Mobile: HDR rendering", "Mobile HDR rendering",
        "0 — LDR pipeline на mobile. 1 — HDR mobile rendering: лучше bloom/tonemap, выше bandwidth и battery drain.",
        "0 — LDR mobile pipeline. 1 — HDR mobile rendering: better bloom/tonemap, higher bandwidth and battery.",
        "Средняя на mobile.", "Medium on mobile.",
        value_hint="0 — слабые телефоны", value_hint_en="0 — weak phones",
    ),
    "r.Mobile.MaxMobileCSMs": E(
        "Mobile: max CSM cascades", "Mobile max CSM cascades",
        "Число cascaded shadow maps на mobile. Меньше — FPS, хуже тени вдали. Больше — качество, тяжелее.",
        "Cascaded shadow map count on mobile. Fewer — FPS, worse distant shadows. More — quality, heavier.",
        "Средняя на mobile open world.", "Medium on mobile open world.",
        min="1", max="4", value_hint="1–2 — mobile", value_hint_en="1–2 — mobile",
        category="Shadows",
    ),
    "r.Mobile.SupportsGen4TAA": E(
        "Mobile: Gen4 TAA", "Mobile supports Gen4 TAA",
        "0 — старый TAA path на mobile. 1 — Gen4 TAA: лучше сглаживание в UE5 mobile, чуть тяжелее.",
        "0 — legacy mobile TAA. 1 — Gen4 TAA: better UE5 mobile AA, slightly heavier.",
        "Средняя.", "Medium.",
        value_hint="1 — UE5 mobile", value_hint_en="1 — UE5 mobile",
        category="PostProcess",
    ),
}

_GROUP_REFLECTION: dict[str, dict] = {
    "r.Reflection.CaptureResolution": E(
        "Reflection captures: разрешение", "Reflection capture resolution",
        "Разрешение cubemap reflection captures. 128 — быстро и грубо. 512+ — чётче зеркала и лужи, больше VRAM.",
        "Reflection capture cubemap resolution. 128 — fast and coarse. 512+ — sharper mirrors and puddles, more VRAM.",
        "VRAM и качество отражений.", "VRAM and reflection quality.",
        min="64", max="2048", value_hint="256 — баланс", value_hint_en="256 — balance",
    ),
    "r.Reflection.Environment": E(
        "Reflection environment", "Reflection environment",
        "0 — без environment reflections. 1 — вкл отражения окружения (SSR + captures): влияет на металл и мокрые поверхности.",
        "0 — no environment reflections. 1 — environment reflections on (SSR + captures): affects metal and wet surfaces.",
        "Средняя–высокая.", "Medium–high.",
        value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.Reflection.MaxRoughness": E(
        "Reflections: max roughness", "Reflection max roughness",
        "Максимальная roughness, при которой ещё считаются отражения. Ниже — меньше матовых отражений, выше FPS.",
        "Max roughness still receiving reflections. Lower — fewer matte reflections, more FPS.",
        "Средняя.", "Medium.",
        min="0", max="1", value_type="float", value_hint="0.6 — типично", value_hint_en="0.6 — typical",
    ),
    "r.Reflection.Method": E(
        "Метод отражений", "Reflection method",
        "Выбор метода отражений (SSR, Lumen, RT — числа зависят от UE). Неверное значение ломает отражения или FPS.",
        "Reflection method choice (SSR, Lumen, RT — numeric depends on UE). Wrong value breaks reflections or FPS.",
        "Очень высокая.", "Very high.",
        max="4", value_hint="не менять без знания", value_hint_en="don't change blindly",
    ),
    "r.Reflection.ScreenSpace": E(
        "Screen-space reflections", "Screen-space reflections",
        "0 — SSR выкл. 1 — вкл экранные отражения: быстрые отражения пола/воды, но только on-screen.",
        "0 — SSR off. 1 — screen-space reflections on: fast floor/water reflections, on-screen only.",
        "Средняя на сценах с SSR.", "Medium on SSR scenes.",
        value_hint="1 — если нет Lumen refl.", value_hint_en="1 — if no Lumen refl.",
    ),
}

_GROUP_PARTICLE: dict[str, dict] = {
    "r.Particle.GPUSimulation": E(
        "Particles: GPU simulation", "Particle GPU simulation",
        "0 — CPU симуляция частиц. 1 — GPU particles: больше частиц при том же CPU, выше нагрузка на GPU.",
        "0 — CPU particle simulation. 1 — GPU particles: more particles for same CPU, higher GPU load.",
        "Зависит от FX.", "FX-dependent.",
        value_hint="1 — много частиц", value_hint_en="1 — many particles",
    ),
    "r.Particle.Lights": E(
        "Particles: lights", "Particle lights",
        "0 — частицы не освещают сцену как lights. 1 — particle lights: огонь/искры дают свет, тяжело на ночных FX.",
        "0 — particles don't emit scene light. 1 — particle lights: fire/sparks illuminate, heavy on night FX.",
        "Высокая на огненных FX.", "High on fire FX.",
        value_hint="0 — FPS", value_hint_en="0 — FPS",
    ),
    "r.Particle.LODBias": E(
        "Particles: LOD bias", "Particle LOD bias",
        "Bias LOD для particle systems. Положительный — грубее частицы вдали (FPS). Отрицательный — детальнее, тяжелее.",
        "LOD bias for particle systems. Positive — coarser distant particles (FPS). Negative — finer, heavier.",
        "Средняя на FX-heavy уровнях.", "Medium on FX-heavy levels.",
        min="-4", max="4", value_hint="0 — стандарт", value_hint_en="0 — standard",
    ),
}

_GROUP_DEFAULT_FEATURE: dict[str, dict] = {
    "r.DefaultFeature.AmbientOcclusion": E(
        "Default feature: AO", "Default feature ambient occlusion",
        "Включает SSAO по умолчанию для новых проектов/уровней. 0 — выкл базовый AO. 1 — SSAO в default pipeline.",
        "Enables default SSAO for new projects/levels. 0 — base AO off. 1 — SSAO in default pipeline.",
        "Средняя нагрузка SSAO.", "Medium SSAO load.",
        value_hint="1 — большинство игр", value_hint_en="1 — most games",
        category="PostProcess",
    ),
    "r.DefaultFeature.AntiAliasing": E(
        "Default feature: AA", "Default feature anti-aliasing",
        "Default anti-aliasing для проекта. 0 — без AA по умолчанию. 1 — TAA/FXAA включён в default renderer.",
        "Default project anti-aliasing. 0 — no default AA. 1 — TAA/FXAA enabled in default renderer.",
        "Средняя.", "Medium.",
        value_hint="1 — стандарт UE", value_hint_en="1 — UE standard",
        category="PostProcess",
    ),
    "r.DefaultFeature.DepthOfField": E(
        "Default feature: DoF", "Default feature depth of field",
        "0 — DoF выкл в default features. 1 — cinematic depth of field доступен по умолчанию в post-process.",
        "0 — DoF off in default features. 1 — cinematic depth of field available by default in post-process.",
        "Средняя при активном DoF.", "Medium with DoF active.",
        value_hint="0 — геймплей без DoF", value_hint_en="0 — gameplay without DoF",
        category="PostProcess",
    ),
}

_GROUP_VOLUMETRIC_FOG: dict[str, dict] = {
    "r.VolumetricFog.GridPixelSize": E(
        "Volumetric fog: grid pixel size", "Volumetric fog grid pixel size",
        "Размер вокселя volumetric fog в пикселях экрана. Больше — грубее god rays, быстрее. Меньше — детальнее лучи, тяжелее.",
        "Volumetric fog voxel size in screen pixels. Larger — coarser god rays, faster. Smaller — finer rays, heavier.",
        "Очень высокая.", "Very high.",
        min="4", max="128", value_hint="8–16 — баланс", value_hint_en="8–16 — balance",
    ),
    "r.VolumetricFog.GridSizeZ": E(
        "Volumetric fog: grid Z", "Volumetric fog grid size Z",
        "Число слоёв volumetric fog по глубине. Больше — точнее туман по высоте, больше VRAM и GPU.",
        "Volumetric fog depth slices. More — finer height fog, more VRAM and GPU.",
        "Очень высокая.", "Very high.",
        min="32", max="256", value_hint="128 — типично", value_hint_en="128 — typical",
    ),
    "r.VolumetricFog.HistoryMissSupersampleCount": E(
        "Volumetric fog: history supersample", "Volumetric fog history miss supersample count",
        "Сэмплов при промахе temporal history volumetric fog. Больше — меньше шума в лучах, дороже.",
        "Samples on volumetric fog temporal history miss. More — less ray noise, costlier.",
        "Высокая.", "High.",
        min="1", max="16", value_hint="4 — баланс", value_hint_en="4 — balance",
    ),
}

_GROUP_DOF_KERNEL: dict[str, dict] = {
    "r.DOF.Kernel.MaxBackgroundRadius": E(
        "DoF kernel: max background radius", "DoF kernel max background radius",
        "Макс. радиус blur kernel для фона в cinematic DoF. Больше — сильнее размытие дальнего плана, тяжелее.",
        "Max blur kernel radius for background in cinematic DoF. Larger — stronger background blur, heavier.",
        "Средняя при активном DoF.", "Medium with DoF active.",
        min="0", max="32", value_type="float", value_hint="экспертный DoF", value_hint_en="expert DoF",
        category="PostProcess",
    ),
    "r.DOF.Kernel.MaxForegroundRadius": E(
        "DoF kernel: max foreground radius", "DoF kernel max foreground radius",
        "Макс. радиус blur для переднего плана DoF. Влияет на bokeh и «отделение» объекта от фона.",
        "Max foreground DoF blur radius. Affects bokeh and subject separation from background.",
        "Средняя при активном DoF.", "Medium with DoF active.",
        min="0", max="32", value_type="float", value_hint="экспертный DoF", value_hint_en="expert DoF",
        category="PostProcess",
    ),
}

MISC: dict[str, dict] = {
    "r.AmbientOcclusionMaxQuality": E(
        "AO: max quality", "Ambient occlusion max quality",
        "Верхний предел качества SSAO (0–100). 0 — AO почти выкл. 100 — полная детализация углов и контактных теней.",
        "SSAO quality ceiling (0–100). 0 — AO nearly off. 100 — full corner and contact shadow detail.",
        "Средняя нагрузка SSAO.", "Medium SSAO load.",
        min="0", max="100", value_hint="100 — Ultra preset", value_hint_en="100 — Ultra preset",
        category="PostProcess",
    ),
    "r.AmbientOcclusionMipLevelFactor": E(
        "AO: mip level factor", "Ambient occlusion mip level factor",
        "Множитель mip для SSAO sampling. Выше — быстрее, грубее AO. Ниже — детальнее затенение в углах.",
        "Mip multiplier for SSAO sampling. Higher — faster, coarser AO. Lower — finer corner shading.",
        "Средняя.", "Medium.",
        min="0.1", max="4", value_type="float", value_hint="1 — стандарт", value_hint_en="1 — standard",
        category="PostProcess",
    ),
    "r.AnisotropicMaterials": E(
        "Anisotropic materials", "Anisotropic materials",
        "0 — упрощённый shading анизотропных материалов (бархат, CD). 1 — полный anisotropic BRDF — реалистичнее, чуть тяжелее.",
        "0 — simplified anisotropic material shading (velvet, brushed metal). 1 — full anisotropic BRDF — more realistic, slightly heavier.",
        "Низкая–средняя.", "Low–medium.",
        value_hint="1 — если есть aniso материалы", value_hint_en="1 — if aniso materials",
    ),
    "r.AOQuality": E(
        "Качество AO (глоб.)", "Global AO quality",
        "Общий уровень качества ambient occlusion (0–4). 0 — минимум. 4 — максимум SSAO/GTAO деталей.",
        "Global ambient occlusion quality (0–4). 0 — minimum. 4 — max SSAO/GTAO detail.",
        "Средняя.", "Medium.",
        max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
        category="PostProcess",
    ),
    "r.Bloom.ScreenPercentage": E(
        "Bloom: screen percentage", "Bloom screen percentage",
        "Разрешение bloom pass относительно экрана. 100 — full. Ниже — быстрее bloom, возможен blockiness на ярких огнях.",
        "Bloom pass resolution vs screen. 100 — full. Lower — faster bloom, possible blockiness on bright lights.",
        "Низкая–средняя.", "Low–medium.",
        min="25", max="200", value_type="float", value_hint="100 — качество", value_hint_en="100 — quality",
        category="PostProcess",
    ),
    "r.CapsuleShadows": E(
        "Capsule shadows", "Capsule shadows",
        "0 — без capsule shadow approximation для скелетов. 1 — вкл: мягкие contact shadows на персонажах, небольшая доп. нагрузка.",
        "0 — no capsule shadow approximation for skeletons. 1 — on: soft contact shadows on characters, small extra cost.",
        "Средняя на уровнях с NPC.", "Medium on NPC-heavy levels.",
        value_hint="1 — персонажи", value_hint_en="1 — characters",
        category="Shadows",
    ),
    "r.CSM.MaxCascades": E(
        "CSM: max cascades", "CSM max cascades",
        "Число каскадов cascaded shadow maps для солнца (1–4). Больше — стабильнее тени вдали на open world.",
        "Cascaded shadow map count for sun (1–4). More — stabler distant shadows on open world.",
        "Средняя–высокая.", "Medium–high.",
        min="1", max="4", value_hint="4 — open world", value_hint_en="4 — open world",
        category="Shadows",
    ),
    "r.CSM.TransitionScale": E(
        "CSM: transition scale", "CSM transition scale",
        "Масштаб зоны смешивания между CSM cascades. Больше — мягче переходы, возможны «полосы» теней.",
        "CSM cascade blend zone scale. Larger — softer transitions, possible shadow banding.",
        "Косметика теней.", "Shadow cosmetics.",
        min="0.1", max="4", value_type="float", value_hint="1 — стандарт", value_hint_en="1 — standard",
        category="Shadows",
    ),
    "r.CustomDepth": E(
        "Custom depth pass", "Custom depth pass",
        "0 — custom depth pass выкл. 1 — вкл: нужен для outline, некоторых post-process и stencil эффектов.",
        "0 — custom depth pass off. 1 — on: needed for outlines, some post-process and stencil effects.",
        "Низкая–средняя.", "Low–medium.",
        value_hint="1 — если игра использует", value_hint_en="1 — if game uses it",
    ),
    "r.CustomDepthTemporalAAJitter": E(
        "Custom depth: TAA jitter", "Custom depth temporal AA jitter",
        "0 — custom depth без TAA jitter. 1 — вкл jitter: стабильнее outline/post при TAA, чуть шумнее depth.",
        "0 — custom depth without TAA jitter. 1 — jitter on: stabler outlines/post with TAA, slightly noisier depth.",
        "Низкая.", "Low.",
        value_hint="1 — с TAA", value_hint_en="1 — with TAA",
    ),
    "r.D3D12.ExecuteContextInParallel": E(
        "D3D12: parallel execute context", "D3D12 execute context in parallel",
        "0 — последовательный execute на D3D12. 1 — параллельный: может дать FPS на многоядерных CPU, зависит от драйвера.",
        "0 — sequential D3D12 execute. 1 — parallel: may boost FPS on multi-core CPUs, driver-dependent.",
        "Зависит от CPU/GPU.", "CPU/GPU dependent.",
        value_hint="1 — современный PC", value_hint_en="1 — modern PC",
    ),
    "r.D3D12.UseAllowTearing": E(
        "D3D12: allow tearing", "D3D12 use allow tearing",
        "0 — без tearing (vsync-friendly). 1 — allow tearing для низкой latency с G-Sync/FreeSync uncapped FPS.",
        "0 — no tearing (vsync-friendly). 1 — allow tearing for low latency with G-Sync/FreeSync uncapped FPS.",
        "Latency vs tearing.", "Latency vs tearing.",
        value_hint="1 — uncapped + adaptive sync", value_hint_en="1 — uncapped + adaptive sync",
    ),
    "r.DetectAndWarnOfBadDrivers": E(
        "Detect bad drivers", "Detect and warn of bad drivers",
        "True — UE предупреждает о проблемных версиях GPU-драйверов при запуске. False — без проверки.",
        "True — UE warns about known bad GPU driver versions at launch. False — no check.",
        "Только диагностика.", "Diagnostics only.",
        value_type="bool", value_hint="True — безопаснее", value_hint_en="True — safer",
        category="Other",
    ),
    "r.DFShadowQuality": E(
        "Distance field shadow quality", "Distance field shadow quality",
        "Качество теней через mesh distance fields (0–4). Выше — чётче DF shadows на foliage и динамике, тяжелее.",
        "Mesh distance field shadow quality (0–4). Higher — sharper DF shadows on foliage/dynamics, heavier.",
        "Высокая при DF shadows.", "High with DF shadows.",
        max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
        category="Shadows",
    ),
    "r.DiffuseIndirect.Allow": E(
        "Diffuse indirect allow", "Diffuse indirect allow",
        "0 — непрямой diffuse lighting выкл. 1 — вкл indirect diffuse (Lightmass/Lumen/SSGI path зависит от проекта).",
        "0 — indirect diffuse lighting off. 1 — indirect diffuse on (Lightmass/Lumen/SSGI path depends on project).",
        "Очень высокая при GI.", "Very high with GI.",
        value_hint="1 — UE5 GI", value_hint_en="1 — UE5 GI",
    ),
    "r.DisableDistortion": E(
        "Disable distortion", "Disable distortion",
        "0 — heat haze/distortion effects разрешены. 1 — все distortion выкл: FPS на сценах с огнём/магией, плоский heat shimmer.",
        "0 — heat haze/distortion allowed. 1 — all distortion off: FPS on fire/magic scenes, flat heat shimmer.",
        "Низкая–средняя.", "Low–medium.",
        value_hint="0 — если FX нужны", value_hint_en="0 — if FX needed",
    ),
    "r.DynamicGlobalIlluminationMethod": E(
        "Метод dynamic GI", "Dynamic global illumination method",
        "Выбор dynamic GI: None, Lumen, SSGI и т.д. (число зависит от UE). Определяет весь pipeline непрямого света.",
        "Dynamic GI choice: None, Lumen, SSGI, etc. (numeric depends on UE). Defines entire indirect light pipeline.",
        "Очень высокая.", "Very high.",
        max="4", value_hint="Lumen — UE5 default", value_hint_en="Lumen — UE5 default",
    ),
    "r.EarlyZPass": E(
        "Early Z pass", "Early Z pass",
        "0 — без early Z prepass. 1–3 — режимы early Z: может ускорить base pass на GPU с early-z benefit.",
        "0 — no early Z prepass. 1–3 — early Z modes: may speed base pass on early-Z friendly GPUs.",
        "Зависит от GPU.", "GPU dependent.",
        max="3", value_hint="2 — часто default", value_hint_en="2 — often default",
    ),
    "r.EarlyZPassOnlyMaterialMasking": E(
        "Early Z: material masking only", "Early Z pass only material masking",
        "0 — полный early Z pass. 1 — только material masking в early Z: экономия, возможны артефакты прозрачности.",
        "0 — full early Z pass. 1 — material masking only in early Z: savings, possible translucency artifacts.",
        "Низкая–средняя.", "Low–medium.",
        value_hint="не менять без причины", value_hint_en="don't change blindly",
    ),
    "r.EmitterSpawnRateScale": E(
        "Emitter spawn rate scale", "Emitter spawn rate scale",
        "Глобальный множитель частоты spawn частиц/emitters. Ниже 1 — меньше FX, выше FPS. Выше 1 — гуще эффекты.",
        "Global emitter/particle spawn rate multiplier. Below 1 — fewer FX, more FPS. Above 1 — denser effects.",
        "Средняя на FX-heavy сценах.", "Medium on FX-heavy scenes.",
        min="0", max="4", value_type="float", value_hint="1 — норма", value_hint_en="1 — normal",
    ),
    "r.FastBlurThreshold": E(
        "Fast blur threshold", "Fast blur threshold",
        "Порог для переключения на быстрый blur. Выше — чаще cheap blur (FPS), возможен banding на мягких эффектах.",
        "Threshold to switch to fast blur. Higher — more cheap blur (FPS), possible banding on soft effects.",
        "Низкая–средняя.", "Low–medium.",
        min="0", max="16", value_type="float", value_hint="не трогать", value_hint_en="leave alone",
        category="PostProcess",
    ),
    "r.Filter.SizeScale": E(
        "Filter size scale", "Filter size scale",
        "Масштаб фильтра текстур/поста. 1 — норма. Ниже — резче но aliased. Выше — мягче, «мыло».",
        "Texture/post filter scale. 1 — normal. Lower — sharper but aliased. Higher — softer blur.",
        "Косметика и резкость.", "Cosmetics and sharpness.",
        min="0.1", max="4", value_type="float", value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.Foliage.DitheredLOD": E(
        "Foliage: dithered LOD", "Foliage dithered LOD",
        "0 — резкий LOD pop у foliage. 1 — dithered переход: плавнее лес вдали, шум на листве.",
        "0 — hard foliage LOD pop. 1 — dithered transition: smoother distant forest, foliage noise.",
        "Средняя в лесах.", "Medium in forests.",
        value_hint="1 — open world", value_hint_en="1 — open world",
    ),
    "r.Foliage.GrassCullDistanceScale": E(
        "Grass: cull distance scale", "Foliage grass cull distance scale",
        "Множитель дальности отсечения травы. Ниже 1 — трава ближе, FPS. Выше 1 — гуще луга, тяжелее.",
        "Grass cull distance multiplier. Below 1 — closer grass, FPS. Above 1 — denser meadows, heavier.",
        "Средняя–высокая на лугах.", "Medium–high on meadows.",
        min="0.1", max="4", value_type="float", value_hint="0.5–1 — FPS", value_hint_en="0.5–1 — FPS",
    ),
    "r.Foliage.GrassDensity": E(
        "Grass density", "Foliage grass density",
        "Глобальная плотность grass/foliage instances. 1 — как в контенте. 0.5 — половина травы, заметный FPS boost.",
        "Global grass/foliage instance density. 1 — as authored. 0.5 — half grass, noticeable FPS boost.",
        "Очень высокая на лугах.", "Very high on meadows.",
        min="0", max="2", value_type="float", value_hint="1 — авторский", value_hint_en="1 — authored",
    ),
    "r.Foliage.Wind": E(
        "Foliage wind", "Foliage wind",
        "0 — без wind animation у foliage. 1 — вкл: колышется трава и листва, небольшая CPU/GPU нагрузка.",
        "0 — no foliage wind animation. 1 — on: grass and leaves sway, small CPU/GPU cost.",
        "Низкая–средняя.", "Low–medium.",
        value_hint="1 — open world", value_hint_en="1 — open world",
    ),
    "r.ForwardShading": E(
        "Forward shading", "Forward shading",
        "0 — deferred shading (стандарт UE). 1 — forward shading: для VR/mobile, ограниченные lights и post.",
        "0 — deferred shading (UE standard). 1 — forward shading: for VR/mobile, limited lights and post.",
        "Сильно меняет pipeline.", "Strong pipeline change.",
        value_hint="0 — PC/консоль", value_hint_en="0 — PC/console",
    ),
    "r.GBufferFormat": E(
        "GBuffer format", "GBuffer format",
        "Формат GBuffer (битность каналов). Меньше — экономия bandwidth, риск banding. Больше — точнее материалы.",
        "GBuffer format (channel bit depth). Lower — bandwidth savings, banding risk. Higher — more accurate materials.",
        "Средняя.", "Medium.",
        min="0", max="5", value_hint="не менять", value_hint_en="don't change",
    ),
    "r.GlobalIllumination.Denoiser": E(
        "GI denoiser", "Global illumination denoiser",
        "0 — без denoiser для GI. 1 — вкл spatial/temporal denoise: чище Lumen/RT GI, небольшая задержка и нагрузка.",
        "0 — no GI denoiser. 1 — spatial/temporal denoise on: cleaner Lumen/RT GI, small lag and load.",
        "Средняя–высокая.", "Medium–high.",
        value_hint="1 — RT/Lumen GI", value_hint_en="1 — RT/Lumen GI",
    ),
    "r.GPUCrashDebugging": E(
        "GPU crash debugging", "GPU crash debugging",
        "True — доп. данные для отладки GPU crash (Aftermath и т.п.). False — меньше overhead, хуже crash dumps.",
        "True — extra GPU crash debug data (Aftermath etc.). False — less overhead, worse crash dumps.",
        "Только отладка.", "Debug only.",
        value_type="bool", value_hint="False в релизе", value_hint_en="False in release",
        category="Other",
    ),
    "r.IndirectLightingCache": E(
        "Indirect lighting cache", "Indirect lighting cache",
        "0 — без ILC для динамических объектов. 1 — вкл indirect lighting cache: быстрее static-ish GI на UE4 path.",
        "0 — no ILC for dynamic objects. 1 — indirect lighting cache on: faster static-ish GI on UE4 path.",
        "Средняя на UE4 GI.", "Medium on UE4 GI.",
        value_hint="0 — чистый Lumen UE5", value_hint_en="0 — pure UE5 Lumen",
    ),
    "r.Landscape.ComponentScreenSizeToUseSubSections": E(
        "Landscape: subsection screen size", "Landscape component screen size to use subsections",
        "Screen size порог для subsection LOD ландшафта. Меньше — детальнее terrain LOD transitions, тяжелее.",
        "Screen-size threshold for landscape subsection LOD. Lower — finer terrain LOD transitions, heavier.",
        "Средняя–высокая open world.", "Medium–high open world.",
        min="0", max="4", value_type="float", value_hint="экспертный terrain", value_hint_en="expert terrain",
    ),
    "r.Landscape.LOD0ScreenSize": E(
        "Landscape: LOD0 screen size", "Landscape LOD0 screen size",
        "Screen size, ниже которого landscape переходит с LOD0. Выше — дольше max detail terrain, тяжелее.",
        "Screen size below which landscape drops from LOD0. Higher — max terrain detail held longer, heavier.",
        "Высокая на open world.", "High on open world.",
        min="0", max="4", value_type="float", value_hint="не завышать", value_hint_en="don't max out",
    ),
    "r.Landscape.LODDistributionScale": E(
        "Landscape: LOD distribution", "Landscape LOD distribution scale",
        "Распределение LOD уровней ландшафта. Выше — LOD transitions дальше от камеры (больше detail near, тяжелее).",
        "Landscape LOD level distribution. Higher — LOD transitions farther from camera (more near detail, heavier).",
        "Высокая.", "High.",
        min="0.1", max="4", value_type="float", value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.LightFunctionQuality": E(
        "Light function quality", "Light function quality",
        "Качество light function materials на прожекторах (0–4). Выше — детальнее gobo/муар, тяжелее.",
        "Light function material quality on spotlights (0–4). Higher — finer gobo patterns, heavier.",
        "Средняя на сценах с gobos.", "Medium on gobo-heavy scenes.",
        max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
    ),
    "r.LightMaxDrawDistanceScale": E(
        "Light max draw distance scale", "Light max draw distance scale",
        "Множитель max draw distance всех lights. Ниже 1 — меньше дальних огней, FPS. Выше — больше огней на горизонте.",
        "All lights max draw distance multiplier. Below 1 — fewer distant lights, FPS. Above — more horizon lights.",
        "Средняя ночью.", "Medium at night.",
        min="0.1", max="4", value_type="float", value_hint="0.5–1 — FPS", value_hint_en="0.5–1 — FPS",
    ),
    "r.LightShaftOcclusion": E(
        "Light shaft occlusion", "Light shaft occlusion",
        "0 — без occlusion для light shafts (god rays). 1 — вкл: реалистичнее лучи сквозь деревья, тяжелее.",
        "0 — no light shaft occlusion. 1 — on: more realistic god rays through trees, heavier.",
        "Средняя на лесных уровнях.", "Medium on forest levels.",
        value_hint="1 — качество лучей", value_hint_en="1 — ray quality",
    ),
    "r.MaxQualityMode": E(
        "Max quality mode", "Max quality mode",
        "0 — обычные scalability limits. 1 — max quality mode: игнорирует часть LOD/quality clamps, «Ultra+» для скриншотов.",
        "0 — normal scalability limits. 1 — max quality mode: ignores some LOD/quality clamps, 'Ultra+' for screenshots.",
        "Очень высокая.", "Very high.",
        value_hint="0 — игра", value_hint_en="0 — gameplay",
    ),
    "r.MipMapLODBias": E(
        "Mip map LOD bias", "Mip map LOD bias",
        "Глобальный bias mipmaps текстур. +1 — blurrier textures, FPS/VRAM. −1 — sharper, больше shimmer и VRAM.",
        "Global texture mipmap LOD bias. +1 — blurrier textures, FPS/VRAM. −1 — sharper, more shimmer and VRAM.",
        "VRAM и резкость.", "VRAM and sharpness.",
        min="-4", max="4", value_hint="0 — норма", value_hint_en="0 — normal",
        category="Textures",
    ),
    "r.MobileHDR": E(
        "Mobile HDR (legacy)", "Mobile HDR legacy",
        "0 — LDR на mobile platforms. 1 — mobile HDR pipeline. Дублирует r.Mobile.HDR в части версий — держите согласованно.",
        "0 — LDR on mobile platforms. 1 — mobile HDR pipeline. Overlaps r.Mobile.HDR on some UE versions — keep consistent.",
        "Средняя mobile.", "Medium mobile.",
        value_hint="как r.Mobile.HDR", value_hint_en="match r.Mobile.HDR",
    ),
    "r.MotionBlur.Amount": E(
        "Motion blur amount", "Motion blur amount",
        "Глобальный множитель motion blur (0 — выкл). Выше 0 — сильнее размытие при движении камеры и объектов.",
        "Global motion blur multiplier (0 — off). Above 0 — stronger blur on camera and object motion.",
        "Средняя при движении.", "Medium in motion.",
        min="0", max="4", value_type="float", value_hint="0 — competitive", value_hint_en="0 — competitive",
        category="PostProcess",
    ),
    "r.MotionBlur.HalfResGather": E(
        "Motion blur half-res gather", "Motion blur half-res gather",
        "0 — full-res motion blur gather. 1 — half-res: быстрее, «грязнее» blur на быстром движении.",
        "0 — full-res motion blur gather. 1 — half-res: faster, dirtier blur on fast motion.",
        "Средняя.", "Medium.",
        value_hint="1 — FPS", value_hint_en="1 — FPS",
        category="PostProcess",
    ),
    "r.ParticleLightQuality": E(
        "Particle light quality", "Particle light quality",
        "Качество освещения от particle lights (0–4). Выше — реалистичнее огонь освещает сцену, тяжелее.",
        "Particle light quality (0–4). Higher — fire more realistically lights scene, heavier.",
        "Высокая на огненных FX.", "High on fire FX.",
        max="4", value_hint="0–2 — FPS", value_hint_en="0–2 — FPS",
    ),
    "r.ParticleLODBias": E(
        "Particle LOD bias (legacy)", "Particle LOD bias legacy",
        "Legacy alias particle LOD bias. Положительный — грубее FX вдали. Согласуйте с r.Particle.LODBias.",
        "Legacy particle LOD bias alias. Positive — coarser distant FX. Align with r.Particle.LODBias.",
        "Средняя.", "Medium.",
        min="-4", max="4", value_hint="как r.Particle.LODBias", value_hint_en="match r.Particle.LODBias",
    ),
    "r.RayTracing.Scene.BuildMode": E(
        "RT scene build mode", "Ray tracing scene build mode",
        "Режим построения RT acceleration structure (0–2). Влияет на время build vs trace performance — экспертный RT параметр.",
        "RT acceleration structure build mode (0–2). Trades build time vs trace performance — expert RT parameter.",
        "RT и load times.", "RT and load times.",
        max="2", value_hint="не менять", value_hint_en="don't change",
    ),
    "r.ReflectionMethod": E(
        "Reflection method (legacy)", "Reflection method legacy",
        "Legacy reflection method selector. Перекрывается r.Reflection.Method в UE5 — меняйте согласованно.",
        "Legacy reflection method selector. Overlaps r.Reflection.Method in UE5 — change consistently.",
        "Очень высокая.", "Very high.",
        max="4", value_hint="см. r.Reflection.Method", value_hint_en="see r.Reflection.Method",
    ),
    "r.Reflections.Allow": E(
        "Reflections allow", "Reflections allow",
        "0 — все environment reflections выкл. 1 — разрешены SSR/Lumen/capture reflections.",
        "0 — all environment reflections off. 1 — SSR/Lumen/capture reflections allowed.",
        "Средняя–высокая.", "Medium–high.",
        value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.Refraction.OffsetQuality": E(
        "Refraction offset quality", "Refraction offset quality",
        "Качество offset refraction для стекла/воды (0–2). Выше — меньше артефактов преломления, тяжелее.",
        "Refraction offset quality for glass/water (0–2). Higher — fewer refraction artifacts, heavier.",
        "Средняя на стекле/воде.", "Medium on glass/water.",
        max="2", value_hint="2 — качество", value_hint_en="2 — quality",
    ),
    "r.Render.Quality": E(
        "Качество рендера", "Render quality",
        "Глобальный переключатель качества отрисовки в Engine.ini — усиливает или ослабляет пресеты графики. 0 — минимум эффектов. 4 — максимум, как Ultra.",
        "Global render quality switch in Engine.ini — boosts or weakens graphics presets. 0 — minimum effects. 4 — maximum, like Ultra.",
        "Очень сильно влияет на FPS.", "Very strong FPS impact.",
        max="4", value_hint="0–4", value_hint_en="0–4",
    ),
    "r.RenderTargetPoolMin": E(
        "Render target pool min", "Render target pool minimum",
        "Минимальный размер пула render targets (MB). Ниже — меньше VRAM резерв, риск stall при spike. Выше — запас, больше VRAM.",
        "Minimum render target pool size (MB). Lower — less VRAM reserve, stall risk on spikes. Higher — headroom, more VRAM.",
        "VRAM.", "VRAM.",
        min="100", max="2000", value_hint="300–400 — типично", value_hint_en="300–400 — typical",
    ),
    "r.RHICmdBypass": E(
        "RHI command bypass", "RHI command bypass",
        "0 — нормальный RHI command list. 1 — bypass для отладки rendering thread deadlocks. Только диагностика.",
        "0 — normal RHI command list. 1 — bypass for rendering thread deadlock debugging. Diagnostics only.",
        "Только отладка.", "Debug only.",
        value_hint="0 — всегда в игре", value_hint_en="0 — always in game",
        category="Other",
    ),
    "r.SceneCaptureDepthPrepass": E(
        "Scene capture depth prepass", "Scene capture depth prepass",
        "0 — scene capture без depth prepass. 1 — вкл: точнее captures для minimap/portrait, чуть дороже.",
        "0 — scene capture without depth prepass. 1 — on: finer minimap/portrait captures, slightly costlier.",
        "Низкая.", "Low.",
        value_hint="1 — если capture артефакты", value_hint_en="1 — if capture artifacts",
    ),
    "r.SceneColorFormat": E(
        "Scene color format", "Scene color format",
        "Формат scene color buffer (bit depth). Ниже — экономия bandwidth, риск banding в HDR. Экспертный параметр.",
        "Scene color buffer format (bit depth). Lower — bandwidth savings, HDR banding risk. Expert parameter.",
        "Средняя.", "Medium.",
        min="0", max="5", value_hint="не менять", value_hint_en="don't change",
    ),
    "r.SceneDepthHZBAsyncCompute": E(
        "Scene depth HZB async compute", "Scene depth HZB async compute",
        "0 — HZB build на graphics queue. 1 — async compute для HZB: может ускорить SSR/AO на современных GPU.",
        "0 — HZB build on graphics queue. 1 — async compute HZB: may speed SSR/AO on modern GPUs.",
        "Зависит от GPU.", "GPU dependent.",
        value_hint="1 — современный GPU", value_hint_en="1 — modern GPU",
    ),
    "r.ScreenProbeGather.ScreenTraces": E(
        "Screen probe gather: screen traces", "Screen probe gather screen traces",
        "0 — без screen traces в probe gather (Lumen/SSGI). 1 — вкл: лучше GI/reflections за экраном, тяжелее.",
        "0 — no screen traces in probe gather (Lumen/SSGI). 1 — on: better off-screen GI/reflections, heavier.",
        "Высокая.", "High.",
        value_hint="1 — Lumen quality", value_hint_en="1 — Lumen quality",
    ),
    "r.ScreenSpaceReflectionQuality": E(
        "SSR quality", "Screen space reflection quality",
        "Качество screen-space reflections (0–4). 0 — SSR off/low. 4 — max SSR iterations и roughness response.",
        "Screen-space reflection quality (0–4). 0 — SSR off/low. 4 — max SSR iterations and roughness response.",
        "Средняя–высокая.", "Medium–high.",
        max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
    ),
    "r.ScreenSpaceShadows": E(
        "Screen space shadows", "Screen space shadows",
        "0 — без contact shadows через screen-space. 1 — вкл SSS: sharper contact shadows у солнца, средняя нагрузка.",
        "0 — no screen-space contact shadows. 1 — SSS on: sharper sun contact shadows, medium load.",
        "Средняя.", "Medium.",
        value_hint="1 — open world sun", value_hint_en="1 — open world sun",
        category="Shadows",
    ),
    "r.SeparateTranslucencyPass": E(
        "Separate translucency pass", "Separate translucency pass",
        "0 — translucency в основном pass. 1 — отдельный pass: лучше сортировка стекла/частиц, выше fill rate.",
        "0 — translucency in main pass. 1 — separate pass: better glass/particle sort, higher fill rate.",
        "Средняя–высокая.", "Medium–high.",
        value_hint="1 — много прозрачности", value_hint_en="1 — heavy translucency",
    ),
    "r.Shadow.MaxCSMResolution": E(
        "Max CSM resolution", "Shadow max CSM resolution",
        "Макс. разрешение cascaded shadow maps солнца. 2048 — баланс. 4096 — ultra sharp shadows, heavy VRAM.",
        "Max cascaded sun shadow map resolution. 2048 — balance. 4096 — ultra sharp shadows, heavy VRAM.",
        "VRAM и качество солнца.", "VRAM and sun quality.",
        min="512", max="4096", value_hint="2048 — баланс", value_hint_en="2048 — balance",
        category="Shadows",
    ),
    "r.SkeletalMeshLODBias": E(
        "Skeletal mesh LOD bias", "Skeletal mesh LOD bias",
        "Bias LOD скелетных мешей (персонажи). +1 — грубее NPC вдали, FPS. −1 — детальнее, тяжелее.",
        "Skeletal mesh LOD bias (characters). +1 — coarser distant NPCs, FPS. −1 — finer, heavier.",
        "Средняя на уровнях с NPC.", "Medium on NPC levels.",
        min="-4", max="4", value_hint="0 — стандарт", value_hint_en="0 — standard",
    ),
    "r.Sky.Atmosphere": E(
        "Sky atmosphere (legacy toggle)", "Sky atmosphere legacy toggle",
        "0 — без sky atmosphere. 1 — вкл physically based sky — нужен для UE5 sky/atmosphere и realistic sun.",
        "0 — no sky atmosphere. 1 — physically based sky on — needed for UE5 sky/atmosphere and realistic sun.",
        "Средняя на открытом небе.", "Medium under open sky.",
        value_hint="1 — UE5 outdoor", value_hint_en="1 — UE5 outdoor",
    ),
    "r.Sky.AtmosphereAsyncCompute": E(
        "Sky atmosphere async compute", "Sky atmosphere async compute",
        "0 — sky atmosphere на graphics queue. 1 — async compute: может дать FPS, зависит от GPU.",
        "0 — sky atmosphere on graphics queue. 1 — async compute: may boost FPS, GPU-dependent.",
        "Зависит от GPU.", "GPU dependent.",
        value_hint="1 — современный GPU", value_hint_en="1 — modern GPU",
    ),
    "r.Sky.LightSampleCountScale": E(
        "Sky light sample count scale", "Sky light sample count scale",
        "Множитель сэмплов skylight capture. 1 — норма. Ниже — быстрее обновление sky light, шумнее GI.",
        "Skylight capture sample multiplier. 1 — normal. Lower — faster sky light updates, noisier GI.",
        "Средняя.", "Medium.",
        min="0.1", max="4", value_type="float", value_hint="1 — стандарт", value_hint_en="1 — standard",
    ),
    "r.SkyAtmosphereAsyncCompute": E(
        "SkyAtmosphere async compute", "SkyAtmosphere async compute",
        "Дублирует r.Sky.AtmosphereAsyncCompute в части версий — async compute path для SkyAtmosphere pass.",
        "Duplicates r.Sky.AtmosphereAsyncCompute on some versions — async compute path for SkyAtmosphere pass.",
        "Зависит от GPU.", "GPU dependent.",
        value_hint="согласовать с r.Sky.*", value_hint_en="align with r.Sky.*",
    ),
    "r.SkyLight.RealTimeReflectionCapture": E(
        "Skylight real-time reflection capture", "Skylight real-time reflection capture",
        "0 — статический skylight capture. 1 — real-time recapture: отражения неба меняются с TOD, тяжелее.",
        "0 — static skylight capture. 1 — real-time recapture: sky reflections follow TOD, heavier.",
        "Средняя–высокая.", "Medium–high.",
        value_hint="1 — dynamic TOD", value_hint_en="1 — dynamic TOD",
    ),
    "r.SkylightIntensityMultiplier": E(
        "Skylight intensity multiplier", "Skylight intensity multiplier",
        "Глобальный множитель яркости skylight. 1 — норма. Выше — пересвет outdoor GI. Ниже — темнее exteriors.",
        "Global skylight brightness multiplier. 1 — normal. Higher — blown outdoor GI. Lower — darker exteriors.",
        "Косметика GI.", "GI cosmetics.",
        min="0", max="4", value_type="float", value_hint="1 — норма", value_hint_en="1 — normal",
    ),
    "r.SkyQuality": E(
        "Sky quality", "Sky quality",
        "Общий уровень качества неба (0–4). Ниже — упрощённый sky rendering. Выше — детальнее sun/sky/atmosphere.",
        "Overall sky quality (0–4). Lower — simplified sky rendering. Higher — finer sun/sky/atmosphere.",
        "Средняя на open world.", "Medium on open world.",
        max="4", value_hint="2 — баланс", value_hint_en="2 — balance",
    ),
    "r.SSR.HalfResSceneColor": E(
        "SSR half-res scene color", "SSR half-res scene color",
        "0 — SSR на full-res scene color. 1 — half-res: быстрее SSR, «мыльнее» отражения пола и воды.",
        "0 — SSR on full-res scene color. 1 — half-res: faster SSR, blurrier floor/water reflections.",
        "Средняя.", "Medium.",
        value_hint="1 — FPS", value_hint_en="1 — FPS",
    ),
    "r.SSS.HalfRes": E(
        "SSS half-res", "Subsurface scattering half-res",
        "0 — subsurface scattering full-res. 1 — half-res SSS: быстрее кожа/листья, менее мягкий subsurface.",
        "0 — full-res subsurface scattering. 1 — half-res SSS: faster skin/foliage, less soft subsurface.",
        "Средняя на персонажах.", "Medium on characters.",
        value_hint="1 — FPS", value_hint_en="1 — FPS",
    ),
    "r.SSS.SampleSet": E(
        "SSS sample set", "Subsurface scattering sample set",
        "Набор сэмплов SSS (0–2). Больше — качественнее translucency кожи и воска, тяжелее.",
        "SSS sample set (0–2). Higher — better skin/wax translucency, heavier.",
        "Средняя.", "Medium.",
        max="2", value_hint="2 — персонажи", value_hint_en="2 — characters",
    ),
    "r.Tonemapper.GrainQuantization": E(
        "Tonemapper grain quantization", "Tonemapper grain quantization",
        "0 — полный grain dither в tonemapper. 1 — quantized grain: меньше banding, чуть «цифровее» зерно.",
        "0 — full tonemapper grain dither. 1 — quantized grain: less banding, slightly more digital grain.",
        "Косметика HDR.", "HDR cosmetics.",
        value_hint="по вкусу", value_hint_en="preference",
        category="PostProcess",
    ),
    "r.TranslucencyLightingVolumeDim": E(
        "Translucency lighting volume dim", "Translucency lighting volume dimension",
        "Размер 3D volume для translucency lighting (64–512). Меньше — быстрее дым/стекло, грубее lighting.",
        "3D translucency lighting volume size (64–512). Smaller — faster smoke/glass, coarser lighting.",
        "Средняя–высокая.", "Medium–high.",
        min="32", max="512", value_hint="64 — FPS", value_hint_en="64 — FPS",
    ),
    "r.TranslucencyVolumeBlur": E(
        "Translucency volume blur", "Translucency volume blur",
        "0 — без blur translucency volume. 1 — вкл blur: мягче свет через дым, небольшая доп. нагрузка.",
        "0 — no translucency volume blur. 1 — blur on: softer light through smoke, small extra cost.",
        "Средняя.", "Medium.",
        value_hint="1 — качество дыма", value_hint_en="1 — smoke quality",
    ),
    "r.VT.MaxAnisotropy": E(
        "Virtual textures: max anisotropy", "Virtual textures max anisotropy",
        "Макс. anisotropic filtering для virtual textures. 4 — быстрее. 8 — sharper VT на углах, чуть тяжелее.",
        "Max anisotropic filtering for virtual textures. 4 — faster. 8 — sharper VT at angles, slightly heavier.",
        "Низкая–средняя.", "Low–medium.",
        min="1", max="16", value_hint="8 — баланс", value_hint_en="8 — balance",
        category="Textures",
    ),
}

_PREFIX_GROUPS: list[tuple[str, dict[str, dict]]] = [
    ("r.Shadow.Virtual.", _GROUP_SHADOW_VIRTUAL),
    ("r.TSR.", _GROUP_TSR),
    ("r.SkyAtmosphere.", _GROUP_SKY_ATMOSPHERE),
    ("r.Streaming.", _GROUP_STREAMING),
    ("s.", _GROUP_STREAMING_SETTINGS),
    ("r.LumenScene.", _GROUP_LUMEN_SCENE),
    ("r.HairStrands.", _GROUP_HAIR_STRANDS),
    ("r.Mobile.", _GROUP_MOBILE),
    ("r.Reflection.", _GROUP_REFLECTION),
    ("r.Particle.", _GROUP_PARTICLE),
    ("r.DefaultFeature.", _GROUP_DEFAULT_FEATURE),
    ("r.VolumetricFog.", _GROUP_VOLUMETRIC_FOG),
    ("r.DOF.Kernel.", _GROUP_DOF_KERNEL),
]


def _match_fog(key: str) -> bool:
    return key == "r.Fog" or key.startswith("r.Fog.") or key in ("r.FogDensity", "r.FogHeightFalloff")


def _match_hetero(key: str) -> bool:
    return key == "r.HeterogeneousVolumes" or key.startswith("r.HeterogeneousVolumes.")


def build_misc(key: str) -> dict | None:
    """Return tier-A entry for misc v6 keys, or None if unknown."""
    if _match_fog(key):
        return _GROUP_FOG.get(key)
    if _match_hetero(key):
        return _GROUP_HETEROGENEOUS_VOLUMES.get(key)
    for prefix, table in _PREFIX_GROUPS:
        if key.startswith(prefix):
            return table.get(key)
    return MISC.get(key)


def _validate() -> None:
    missing = [k for k in sorted(REQUIRED_KEYS) if build_misc(k) is None]
    if missing:
        raise SystemExit(f"tier_a_v6_misc missing {len(missing)} keys:\n  " + "\n  ".join(missing))
    extra_misc = set(MISC) - REQUIRED_KEYS
    if "r.Render.Quality" not in MISC:
        raise SystemExit("r.Render.Quality must be in MISC")
    # r.Render.Quality is optional extra, not in REQUIRED_KEYS
    _ = extra_misc


if __name__ == "__main__":
    _validate()
    print(f"OK: {len(REQUIRED_KEYS)} required keys + r.Render.Quality")
