; GSM universal preset — Cinematic
Techniques=Clarity,Vignette,AdaptiveSharpen
TechniqueSorting=Clarity@Clarity,Vignette@Vignette,AdaptiveSharpen@Adaptive Sharpen

[Clarity.fx]
ClarityRadius=2
ClarityOffset=1.500000
ClarityBlendIfDark=50
ClarityBlendIfLight=205
ClarityViewBlendIfMask=0
ClarityMaskContrast=0.000000
ClarityMaskIntensity=0.350000

[Vignette.fx]
Amount=-0.350000
Slope=8
Radius=1.000000
Ratio=0.000000

[AdaptiveSharpen.fx]
curveslope=0.500000
curve_height=1.000000
sharp_strength=0.300000
scale_lim=0.100000
scale_cs=0.050000
