#!/usr/bin/env python3
"""Hand-authored tier A overlays for former semi-tier-B keys (batch 5)."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "tier_a_expansion_v5.json"

FX = {
    "AmbientOcclusion": ("затенение в углах (SSAO)", "corner ambient occlusion (SSAO)", "PostProcess"),
    "AntiAliasing": ("сглаживание краёв (AA)", "edge anti-aliasing (AA)", "PostProcess"),
    "Bloom": ("свечение ярких источников (bloom)", "bright source bloom", "PostProcess"),
    "ChromaticAberration": ("хроматическая аберрация", "chromatic aberration", "PostProcess"),
    "ColorGrading": ("цветокоррекция", "color grading", "PostProcess"),
    "DepthOfField": ("глубина резкости (DoF)", "depth of field (DoF)", "PostProcess"),
    "Grain": ("плёночное зерно", "film grain", "PostProcess"),
    "LensFlares": ("блики объектива", "lens flares", "PostProcess"),
    "MotionBlur": ("размытие в движении", "motion blur", "PostProcess"),
    "SceneFringe": ("цветовая окантовка по краям", "scene color fringe", "PostProcess"),
    "ScreenSpaceReflections": ("экранные отражения (SSR)", "screen-space reflections (SSR)", "PostProcess"),
    "Tonemapper": ("тонмаппер / HDR", "tonemapper / HDR", "PostProcess"),
    "Vignette": ("виньетирование по краям", "edge vignette", "PostProcess"),
}

FX_SUFFIX = {
    "Enable": {
        "title_ru": "{topic}: вкл/выкл",
        "title_en": "{topic}: on/off",
        "desc_ru": "0 — {topic} выключен. 1 — включён: влияет на финальную картинку после рендера.",
        "desc_en": "0 — {topic} off. 1 — on: affects the final post-processed image.",
        "impact_ru": "Зависит от эффекта — от косметики до средней нагрузки.",
        "impact_en": "Depends on effect — cosmetic to medium load.",
        "min": "0",
        "max": "1",
        "type": "int",
    },
    "Quality": {
        "title_ru": "{topic}: качество",
        "title_en": "{topic}: quality",
        "desc_ru": "Детализация {topic}. 0 — грубо и быстро. 4 — максимум качества, тяжелее для GPU.",
        "desc_en": "{topic} detail. 0 — coarse and fast. 4 — max quality, heavier GPU.",
        "impact_ru": "Средняя нагрузка на постобработку.",
        "impact_en": "Medium post-process load.",
        "min": "0",
        "max": "4",
        "type": "int",
    },
    "Intensity": {
        "title_ru": "{topic}: интенсивность",
        "title_en": "{topic}: intensity",
        "desc_ru": "Сила {topic}. 0 — почти не видно. 1 — как задумано. Выше 1 — перебор.",
        "desc_en": "{topic} strength. 0 — barely visible. 1 — as intended. Above 1 — overdone.",
        "impact_ru": "В основном косметика.",
        "impact_en": "Mostly cosmetic.",
        "min": "0",
        "max": "4",
        "type": "float",
    },
    "Max": {
        "title_ru": "{topic}: верхний предел",
        "title_en": "{topic}: max clamp",
        "desc_ru": "Ограничивает максимальный вклад {topic} — полезно против пересвета в ini.",
        "desc_en": "Caps maximum {topic} — useful against blown-out ini values.",
        "impact_ru": "Косметика.",
        "impact_en": "Cosmetic.",
        "min": "0",
        "max": "4",
        "type": "float",
    },
    "Distance": {
        "title_ru": "{topic}: дальность",
        "title_en": "{topic}: distance",
        "desc_ru": "Дальность отрисовки или влияния {topic}. Меньше — экономия FPS на горизонте.",
        "desc_en": "Draw or influence distance for {topic}. Lower — horizon FPS savings.",
        "impact_ru": "Средняя на open world.",
        "impact_en": "Medium open world.",
        "min": "0",
        "max": "100000",
        "type": "float",
    },
    "Count": {
        "title_ru": "{topic}: плотность",
        "title_en": "{topic}: density",
        "desc_ru": "Число или плотность слоёв {topic}. Выше — гуще облака, тяжелее для GPU.",
        "desc_en": "Layer count or density for {topic}. Higher — denser clouds, heavier GPU.",
        "impact_ru": "Средняя на открытом небе.",
        "impact_en": "Medium under open sky.",
        "min": "0",
        "max": "4",
        "type": "int",
    },
}

INDIVIDUAL: dict[str, dict] = {
    "r.AllowOcclusionQueries": {
        "title": "Occlusion queries",
        "title_en": "Occlusion queries",
        "description": "0 — движок не использует occlusion queries для скрытия невидимой геометрии. 1 — вкл: может дать FPS на плотных уровнях, но иногда ломает видимость объектов.",
        "description_en": "0 — engine skips occlusion queries for hidden geometry. 1 — on: may boost FPS on dense levels but can break object visibility.",
        "impact": "Может помочь или навредить FPS — тестируйте.",
        "impact_en": "May help or hurt FPS — test in-game.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — по умолчанию",
        "value_hint_en": "1 — default",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.AllowStaticLighting": {
        "title": "Статическое освещение",
        "title_en": "Static lighting",
        "description": "0 — только динамический свет (медленнее, гибче). 1 — baked static lighting разрешён — быстрее там, где карта запечена.",
        "description_en": "0 — dynamic lighting only (slower, flexible). 1 — baked static lighting allowed — faster on baked maps.",
        "impact": "Сильно зависит от игры — не выключайте без причины.",
        "impact_en": "Highly game-dependent — don't disable without reason.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — большинство UE-игр",
        "value_hint_en": "1 — most UE games",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.AntiAliasingMethod": {
        "title": "Метод сглаживания (AA)",
        "title_en": "Anti-aliasing method",
        "description": "Выбор алгоритма AA: FXAA, TAA, MSAA и т.д. (число зависит от версии UE). Неправильное значение может дать «мыло» или «лестницы».",
        "description_en": "AA algorithm choice: FXAA, TAA, MSAA, etc. (numeric depends on UE version). Wrong value may blur or jag.",
        "impact": "Средняя нагрузка. Согласуйте с TSR/DLSS в игре.",
        "impact_en": "Medium load. Align with in-game TSR/DLSS.",
        "min": "0",
        "max": "8",
        "value_hint": "не менять без знания метода",
        "value_hint_en": "don't change without knowing method",
        "category": "PostProcess",
        "value_type": "int",
    },
    "r.AsyncCompute": {
        "title": "Async compute (глобально)",
        "title_en": "Global async compute",
        "description": "Разрешает async compute для части проходов рендера. 0 — классический путь. 1 — параллельные задачи на GPU, может помочь или навредить на старых драйверах.",
        "description_en": "Allows async compute for some render passes. 0 — classic path. 1 — parallel GPU work, may help or hurt on old drivers.",
        "impact": "Зависит от GPU и драйвера.",
        "impact_en": "GPU and driver dependent.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — обычно OK на современных GPU",
        "value_hint_en": "1 — usually OK on modern GPUs",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.BasePassVelocity": {
        "title": "Velocity в base pass",
        "title_en": "Base pass velocity",
        "description": "0 — velocity не пишется в base pass. 1 — вкл для motion blur, TSR, frame gen. Не выключайте, если используете upscaler.",
        "description_en": "0 — no velocity in base pass. 1 — on for motion blur, TSR, frame gen. Don't disable if using upscaler.",
        "impact": "Небольшая нагрузка при 1.",
        "impact_en": "Small load at 1.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — для TSR/motion blur",
        "value_hint_en": "1 — for TSR/motion blur",
        "category": "PostProcess",
        "value_type": "int",
    },
    "r.BloomIntensity": {
        "title": "Интенсивность bloom (глобально)",
        "title_en": "Global bloom intensity",
        "description": "Множитель яркости bloom поверх настроек игры. 1 — норма. Выше — «пересвеченное» солнце и огни. 0 — bloom почти не виден.",
        "description_en": "Bloom brightness multiplier on top of game settings. 1 — normal. Higher — blown-out sun and lights. 0 — bloom barely visible.",
        "impact": "Косметика, низкая нагрузка.",
        "impact_en": "Cosmetic, low load.",
        "min": "0",
        "max": "4",
        "value_hint": "0.5–1 — норма",
        "value_hint_en": "0.5–1 — normal",
        "category": "PostProcess",
        "value_type": "float",
    },
    "r.ClearCoatNormal": {
        "title": "Clear coat normal maps",
        "title_en": "Clear coat normals",
        "description": "0 — упрощённые блики на лакированных/мокрых поверхностях. 1 — полноценные clear coat normals — реалистичнее капоты, кожа, мокрый металл.",
        "description_en": "0 — simplified highlights on lacquered/wet surfaces. 1 — full clear coat normals — more realistic hoods, leather, wet metal.",
        "impact": "Низкая–средняя нагрузка.",
        "impact_en": "Low–medium load.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — если есть clear coat материалы",
        "value_hint_en": "1 — if clear coat materials exist",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.MeshReductionModule": {
        "title": "Модуль упрощения мешей",
        "title_en": "Mesh reduction module",
        "description": "Технический переключатель модуля LOD/reduction. Меняйте только при проблемах с LOD или по документации UE — на геймплей обычно не влияет напрямую.",
        "description_en": "Technical LOD/reduction module toggle. Change only for LOD issues or per UE docs — usually no direct gameplay effect.",
        "impact": "Технический параметр.",
        "impact_en": "Technical parameter.",
        "min": "0",
        "max": "1",
        "value_hint": "не трогать",
        "value_hint_en": "leave alone",
        "category": "Other",
        "value_type": "int",
    },
    "r.SkyAtmosphere.AerialPerspectiveLUT.FastApplyOnOpaque": {
        "title": "Sky Atmosphere: быстрый aerial perspective",
        "title_en": "Sky atmosphere fast aerial perspective",
        "description": "0 — полный расчёт aerial perspective для неба. 1 — ускоренный LUT на непрозрачных поверхностях: быстрее, чуть менее точная дымка на горизонте.",
        "description_en": "0 — full aerial perspective for sky. 1 — fast LUT on opaque surfaces: faster, slightly less accurate horizon haze.",
        "impact": "Средняя на открытых картах.",
        "impact_en": "Medium on open maps.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — FPS на open world",
        "value_hint_en": "1 — open-world FPS",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.Lumen.FinalGatherQuality": {
        "title": "Lumen: качество final gather",
        "title_en": "Lumen final gather quality",
        "description": "Детализация финального сбора непрямого света Lumen. 0 — быстро, шумнее в тёмных углах. 4 — чище GI, но сильно тяжелее.",
        "description_en": "Lumen indirect light final gather detail. 0 — fast, noisier dark corners. 4 — cleaner GI but much heavier.",
        "impact": "Очень высокая при 3–4.",
        "impact_en": "Very high at 3–4.",
        "min": "0",
        "max": "4",
        "value_hint": "1–2 — баланс",
        "value_hint_en": "1–2 — balance",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.Lumen.HardwareRayTracing": {
        "title": "Lumen: аппаратная трассировка",
        "title_en": "Lumen hardware ray tracing",
        "description": "0 — Lumen GI/reflections без RT-ядер (быстрее на старых GPU). 1 — Lumen использует hardware RT — точнее, но нужен RTX/RDNA2+.",
        "description_en": "0 — Lumen GI/reflections without RT cores (faster on older GPUs). 1 — Lumen uses hardware RT — more accurate but needs RTX/RDNA2+.",
        "impact": "Очень высокая при 1.",
        "impact_en": "Very high at 1.",
        "min": "0",
        "max": "1",
        "value_hint": "0 — без RT, 1 — с RT",
        "value_hint_en": "0 — no RT, 1 — with RT",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.Lumen.MaxTraceDistance": {
        "title": "Lumen: макс. дальность лучей",
        "title_en": "Lumen max trace distance",
        "description": "Как далеко Lumen «видит» для отражений и GI. Меньше — экономия FPS, отражения обрываются ближе. Больше — дальше видны отражения неба и интерьеров.",
        "description_en": "How far Lumen traces for reflections and GI. Shorter — FPS savings, reflections cut off sooner. Longer — sky and interior reflections farther.",
        "impact": "Средняя–высокая на open world.",
        "impact_en": "Medium–high open world.",
        "min": "1000",
        "max": "100000",
        "value_hint": "уменьшить для FPS",
        "value_hint_en": "lower for FPS",
        "category": "Rendering",
        "value_type": "float",
    },
    "r.Lumen.SceneLightingUpdateSpeed": {
        "title": "Lumen: скорость обновления освещения",
        "title_en": "Lumen scene lighting update speed",
        "description": "Как быстро Lumen подстраивает GI под смену времени суток или динамический свет. Выше — быстрее реакция, но больше мерцания. Ниже — стабильнее, но «запаздывание».",
        "description_en": "How fast Lumen adapts GI to time-of-day or dynamic light changes. Higher — faster response but more flicker. Lower — stabler but laggy.",
        "impact": "Средняя нагрузка.",
        "impact_en": "Medium load.",
        "min": "0.1",
        "max": "8",
        "value_hint": "1 — баланс",
        "value_hint_en": "1 — balance",
        "category": "Rendering",
        "value_type": "float",
    },
    "r.Nanite.AllowTessellation": {
        "title": "Nanite: tessellation",
        "title_en": "Nanite tessellation",
        "description": "0 — Nanite без tessellation (быстрее). 1 — вкл displacement/tessellation на Nanite-мешах — больше деталей рельефа, но тяжелее.",
        "description_en": "0 — Nanite without tessellation (faster). 1 — displacement/tessellation on Nanite meshes — more surface detail but heavier.",
        "impact": "Высокая при 1.",
        "impact_en": "High at 1.",
        "min": "0",
        "max": "1",
        "value_hint": "0 — FPS",
        "value_hint_en": "0 — FPS",
        "category": "Rendering",
        "value_type": "int",
    },
    "r.Nanite.ImpostorDistanceScale": {
        "title": "Nanite: дистанция impostor",
        "title_en": "Nanite impostor distance scale",
        "description": "Множитель расстояния, на котором Nanite подменяет дальние объекты упрощёнными impostor. Больше 1 — дольше полная детализация (красивее, тяжелее).",
        "description_en": "Distance multiplier before Nanite swaps distant objects to impostors. Above 1 — full detail held longer (prettier, heavier).",
        "impact": "Сильно на open world.",
        "impact_en": "Strong on open world.",
        "min": "0.1",
        "max": "4",
        "value_hint": "1 — стандарт",
        "value_hint_en": "1 — default",
        "category": "Rendering",
        "value_type": "float",
    },
    "r.Nanite.MaxPixelsPerEdge": {
        "title": "Nanite: детализация (pixels per edge)",
        "title_en": "Nanite max pixels per edge",
        "description": "Главный «ползунок» качества Nanite: меньше значение — более детальные мелкие объекты на экране, но тяжелее GPU. Больше — грубее, быстрее.",
        "description_en": "Main Nanite quality knob: lower value — finer small on-screen detail but heavier GPU. Higher — coarser, faster.",
        "impact": "Критично для FPS в UE5.",
        "impact_en": "Critical for UE5 FPS.",
        "min": "1",
        "max": "8",
        "value_hint": "2 — баланс, 4+ — FPS",
        "value_hint_en": "2 — balance, 4+ — FPS",
        "category": "Rendering",
        "value_type": "float",
    },
    "r.Shadow.PreShadowResolutionFactor": {
        "title": "Тени: множитель pre-shadow",
        "title_en": "Pre-shadow resolution factor",
        "description": "Масштабирует разрешение pre-shadow pass. 1 — норма. Ниже — быстрее, мыльнее тени. Выше — чётче, тяжелее.",
        "description_en": "Scales pre-shadow pass resolution. 1 — normal. Lower — faster, blurrier shadows. Higher — sharper, heavier.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "0.1",
        "max": "2",
        "value_hint": "1 — стандарт",
        "value_hint_en": "1 — default",
        "category": "Shadows",
        "value_type": "float",
    },
    "r.Shadow.Quality": {
        "title": "Общее качество теней",
        "title_en": "Overall shadow quality",
        "description": "Глобальный уровень качества теней: фильтрация, разрешение, стабильность. 0 — грубо. 4 — максимум — заметно на FPS.",
        "description_en": "Global shadow quality: filtering, resolution, stability. 0 — coarse. 4 — max — noticeable FPS hit.",
        "impact": "Очень сильно на FPS.",
        "impact_en": "Very strong FPS impact.",
        "min": "0",
        "max": "4",
        "value_hint": "2 — баланс",
        "value_hint_en": "2 — balance",
        "category": "Shadows",
        "value_type": "int",
    },
    "r.Shadow.Virtual.Enable": {
        "title": "Virtual Shadow Maps (VSM)",
        "title_en": "Virtual Shadow Maps enable",
        "description": "0 — классические shadow maps. 1 — VSM UE5: стабильнее тени вдали, но тяжелее. Актуально для UE5 open world.",
        "description_en": "0 — classic shadow maps. 1 — UE5 VSM: stabler distant shadows but heavier. Relevant for UE5 open world.",
        "impact": "Высокая на UE5.",
        "impact_en": "High on UE5.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — UE5 по умолчанию",
        "value_hint_en": "1 — UE5 default",
        "category": "Shadows",
        "value_type": "int",
    },
    "r.Audio.DisableMasterEQ": {
        "title": "Отключить master EQ",
        "title_en": "Disable master EQ",
        "description": "0 — master EQ активен. 1 — выкл глобальный EQ — «плоский» звук, иногда полезно для диагностики.",
        "description_en": "0 — master EQ active. 1 — disable global EQ — flat sound, sometimes useful for debugging.",
        "impact": "На FPS не влияет.",
        "impact_en": "No FPS impact.",
        "min": "0",
        "max": "1",
        "value_hint": "0 — норма",
        "value_hint_en": "0 — normal",
        "category": "Audio",
        "value_type": "int",
    },
    "r.Audio.MaxChannels": {
        "title": "Макс. аудиоканалов",
        "title_en": "Max audio channels",
        "description": "Сколько звуков одновременно может играть. Меньше — экономия CPU, но пропадают дальние звуки. Больше — богаче звук, выше нагрузка.",
        "description_en": "How many sounds can play at once. Lower — CPU savings but missing distant sounds. Higher — richer audio, more load.",
        "impact": "CPU, не GPU.",
        "impact_en": "CPU, not GPU.",
        "min": "16",
        "max": "256",
        "value_hint": "32–64 — баланс",
        "value_hint_en": "32–64 — balance",
        "category": "Audio",
        "value_type": "int",
    },
    "r.Audio.Quality": {
        "title": "Качество аудио",
        "title_en": "Audio quality",
        "description": "0 — упрощённая обработка звука. 1 — полное качество: reverb, occlusion, HRTF если поддерживается.",
        "description_en": "0 — simplified audio processing. 1 — full quality: reverb, occlusion, HRTF if supported.",
        "impact": "Низкая на FPS.",
        "impact_en": "Low FPS impact.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — рекомендуется",
        "value_hint_en": "1 — recommended",
        "category": "Audio",
        "value_type": "int",
    },
}

# PostProcess, DOF, RayTracing, Cloud — add as grouped entries
POSTPROCESS = {
    "AAQuality": ("качество AA", "AA quality"),
    "BloomQuality": ("качество bloom", "bloom quality"),
    "DepthOfFieldQuality": ("качество DoF", "DoF quality"),
    "EyeAdaptationQuality": ("адаптация глаз", "eye adaptation quality"),
    "LensFlareQuality": ("качество lens flare", "lens flare quality"),
    "MotionBlurQuality": ("качество motion blur", "motion blur quality"),
    "Quality": ("общее качество постобработки", "overall post-process quality"),
    "SceneColorFringeQuality": ("качество color fringe", "color fringe quality"),
}

DOF = {
    "Gather.AccumulatorQuality": ("DoF gather: качество аккумулятора", "DoF gather accumulator quality"),
    "Gather.EnableBokehSettings": ("DoF gather: bokeh", "DoF gather bokeh"),
    "Gather.PostfilterMethod": ("DoF gather: postfilter", "DoF gather postfilter"),
    "Gather.ResolutionDivisor": ("DoF gather: делитель разрешения", "DoF gather resolution divisor"),
    "Gather.RingCount": ("DoF gather: число колец", "DoF gather ring count"),
    "Recombine.EnableBokehSettings": ("DoF recombine: bokeh", "DoF recombine bokeh"),
    "Recombine.Quality": ("DoF recombine: качество", "DoF recombine quality"),
    "Scatter.BackgroundCompositing": ("DoF scatter: фон", "DoF scatter background"),
    "Scatter.EnableBokehSettings": ("DoF scatter: bokeh", "DoF scatter bokeh"),
    "Scatter.ForegroundCompositing": ("DoF scatter: передний план", "DoF scatter foreground"),
    "Scatter.MaxSpriteRatio": ("DoF scatter: max sprite ratio", "DoF scatter max sprite ratio"),
    "TemporalAAQuality": ("DoF temporal AA quality", "DoF temporal AA quality"),
}

RT = {
    "AO": ("RT ambient occlusion", "RT ambient occlusion"),
    "GlobalIllumination": ("RT global illumination", "RT global illumination"),
    "Reflections": ("RT reflections", "RT reflections"),
    "SkyLight": ("RT sky light", "RT sky light"),
    "Translucency": ("RT translucency", "RT translucency"),
}

CLOUD_SUFFIX = FX_SUFFIX  # reuse templates

T_KEYS = {
    "t.AdaptiveVirtualTexture": {
        "title": "Adaptive Virtual Texture",
        "title_en": "Adaptive Virtual Texture",
        "description": "0 — AVT выкл. 1 — адаптивные виртуальные текстуры для огромных ландшафтов — экономия VRAM, если игра поддерживает.",
        "description_en": "0 — AVT off. 1 — adaptive virtual textures for huge landscapes — VRAM savings if supported.",
        "impact": "Средняя на open world.",
        "impact_en": "Medium open world.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — если VT в игре",
        "value_hint_en": "1 — if VT in game",
        "category": "Textures",
        "value_type": "int",
    },
    "t.MaxAnisotropy": {
        "title": "Анизотропия (t.*)",
        "title_en": "Anisotropy (t.* namespace)",
        "description": "Аналог r.MaxAnisotropy в namespace t.* — чёткость текстур под углом. 16 — рекомендуется.",
        "description_en": "Like r.MaxAnisotropy in t.* namespace — angled texture sharpness. 16 recommended.",
        "impact": "Почти без FPS.",
        "impact_en": "Almost no FPS cost.",
        "min": "0",
        "max": "16",
        "value_hint": "16",
        "value_hint_en": "16",
        "category": "Textures",
        "value_type": "int",
    },
    "t.MipMapLODBias": {
        "title": "Mip bias (t.*)",
        "title_en": "Mip bias (t.* namespace)",
        "description": "Смещение mip уровня текстур в t.* namespace. +2 — размытие и FPS. 0 — норма.",
        "description_en": "Texture mip offset in t.* namespace. +2 — blur and FPS. 0 — normal.",
        "impact": "VRAM и резкость.",
        "impact_en": "VRAM and sharpness.",
        "min": "-3",
        "max": "15",
        "value_hint": "+2 — экономия",
        "value_hint_en": "+2 — save",
        "category": "Textures",
        "value_type": "float",
    },
    "t.PoolSize": {
        "title": "Пул текстур t.* (MB)",
        "title_en": "Texture pool t.* MB",
        "description": "Размер пула в namespace t.* — см. также r.Streaming.PoolSize. Увеличивайте при фризах подгрузки.",
        "description_en": "Pool size in t.* namespace — see r.Streaming.PoolSize. Raise if streaming hitches.",
        "impact": "VRAM и фризы.",
        "impact_en": "VRAM and hitches.",
        "min": "256",
        "max": "8192",
        "value_hint": "4000+ для 12 GB VRAM",
        "value_hint_en": "4000+ for 12 GB VRAM",
        "category": "Textures",
        "value_type": "int",
    },
    "t.Quality": {
        "title": "Качество текстур (t.*)",
        "title_en": "Texture quality (t.*)",
        "description": "Глобальный уровень качества в t.* namespace. 0 — Low, 3 — Epic.",
        "description_en": "Global quality in t.* namespace. 0 — Low, 3 — Epic.",
        "impact": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "min": "0",
        "max": "3",
        "value_hint": "3 — максимум",
        "value_hint_en": "3 — max",
        "category": "Textures",
        "value_type": "int",
    },
    "t.Streaming": {
        "title": "Стриминг текстур (t.*)",
        "title_en": "Texture streaming (t.*)",
        "description": "0 — упрощённый стриминг. 1 — полный pipeline подгрузки текстур.",
        "description_en": "0 — simplified streaming. 1 — full texture streaming pipeline.",
        "impact": "Фризы и VRAM.",
        "impact_en": "Hitches and VRAM.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — норма",
        "value_hint_en": "1 — normal",
        "category": "Textures",
        "value_type": "int",
    },
    "t.VT": {
        "title": "Virtual Texturing (t.VT)",
        "title_en": "Virtual Texturing (t.VT)",
        "description": "0 — VT выкл. 1 — virtual texturing вкл, если игра использует RVT/VT.",
        "description_en": "0 — VT off. 1 — virtual texturing on if game uses RVT/VT.",
        "impact": "Средняя на open world.",
        "impact_en": "Medium open world.",
        "min": "0",
        "max": "1",
        "value_hint": "по поддержке игры",
        "value_hint_en": "per game support",
        "category": "Textures",
        "value_type": "int",
    },
    "t.Virtual": {
        "title": "Virtual textures (t.Virtual)",
        "title_en": "Virtual textures (t.Virtual)",
        "description": "Переключатель virtual texture pipeline в t.* namespace.",
        "description_en": "Virtual texture pipeline toggle in t.* namespace.",
        "impact": "VRAM и open world.",
        "impact_en": "VRAM and open world.",
        "min": "0",
        "max": "1",
        "value_hint": "1 — если VT активен",
        "value_hint_en": "1 — if VT active",
        "category": "Textures",
        "value_type": "int",
    },
}


def pp_entry(suffix: str, title_ru: str, title_en: str) -> dict:
    return {
        "title": title_ru,
        "title_en": title_en,
        "description": f"Уровень качества {title_ru.lower()} в блоке PostProcess. Выше — детальнее эффект, ниже — экономия FPS.",
        "description_en": f"PostProcess {title_en.lower()} quality level. Higher — more detail, lower — FPS savings.",
        "impact": "Средняя нагрузка на постобработку.",
        "impact_en": "Medium post-process load.",
        "min": "0",
        "max": "4",
        "value_hint": "2 — баланс",
        "value_hint_en": "2 — balance",
        "category": "PostProcess",
        "value_type": "int",
    }


def dof_entry(path: str, title_ru: str, title_en: str) -> dict:
    return {
        "title": title_ru,
        "title_en": title_en,
        "description": f"Тонкая настройка depth of field: {title_ru.lower()}. Влияет на боке и плавность размытия фона. Меняйте только если настраиваете cinematic DoF.",
        "description_en": f"Fine depth of field tuning: {title_en.lower()}. Affects bokeh and background blur smoothness. Change only when tuning cinematic DoF.",
        "impact": "Средняя нагрузка при активном DoF.",
        "impact_en": "Medium load with DoF active.",
        "min": "0",
        "max": "4",
        "value_hint": "экспертный параметр",
        "value_hint_en": "expert parameter",
        "category": "PostProcess",
        "value_type": "int",
    }


def rt_entry(name: str, title_ru: str, title_en: str) -> dict:
    return {
        "title": title_ru,
        "title_en": title_en,
        "description": f"0 — {title_ru} выкл. 1 — вкл hardware ray tracing для этого прохода. Очень тяжело — только на RTX/RDNA2+.",
        "description_en": f"0 — {title_en} off. 1 — hardware RT for this pass. Very heavy — RTX/RDNA2+ only.",
        "impact": "Очень высокая при 1.",
        "impact_en": "Very high at 1.",
        "min": "0",
        "max": "1",
        "value_hint": "0 — FPS, 1 — RT качество",
        "value_hint_en": "0 — FPS, 1 — RT quality",
        "category": "Rendering",
        "value_type": "int",
    }


def fx_entry(effect: str, suffix: str) -> dict:
    topic_ru, topic_en, cat = FX[effect]
    suf = FX_SUFFIX[suffix]
    return {
        "title": suf["title_ru"].format(topic=topic_ru),
        "title_en": suf["title_en"].format(topic=topic_en),
        "description": suf["desc_ru"].format(topic=topic_ru),
        "description_en": suf["desc_en"].format(topic=topic_en),
        "impact": suf["impact_ru"],
        "impact_en": suf["impact_en"],
        "min": suf["min"],
        "max": suf["max"],
        "value_hint": "0–1 или 0–4 по параметру",
        "value_hint_en": "0–1 or 0–4 per param",
        "category": cat,
        "value_type": suf["type"],
    }


def cloud_entry(suffix: str) -> dict:
    topic_ru, topic_en = "облака неба", "sky clouds"
    suf = CLOUD_SUFFIX[suffix]
    return {
        "title": suf["title_ru"].format(topic=topic_ru),
        "title_en": suf["title_en"].format(topic=topic_en),
        "description": suf["desc_ru"].format(topic=topic_ru),
        "description_en": suf["desc_en"].format(topic=topic_en),
        "impact": "Средняя на открытом небе.",
        "impact_en": "Medium under open sky.",
        "min": suf["min"],
        "max": suf["max"],
        "value_hint": "1 — норма",
        "value_hint_en": "1 — normal",
        "category": "Rendering",
        "value_type": suf["type"],
    }


def build_all() -> dict[str, dict]:
    out: dict[str, dict] = dict(INDIVIDUAL)
    out.update(T_KEYS)

    for sfx, (tr, te) in POSTPROCESS.items():
        out[f"r.PostProcess.{sfx}"] = pp_entry(sfx, tr, te)

    for path, (tr, te) in DOF.items():
        out[f"r.DOF.{path}"] = dof_entry(path, tr, te)

    for name, (tr, te) in RT.items():
        out[f"r.RayTracing.{name}"] = rt_entry(name, tr, te)

    for sfx in ("Enable", "Intensity", "Distance"):
        out[f"r.Cloud.{sfx}"] = cloud_entry(sfx)
    out["r.Cloud.Bias"] = {
        "title": "Облака: bias",
        "title_en": "Sky clouds bias",
        "description": "Смещение выборки облаков — убирает артефакты или «плавающие» облака.",
        "description_en": "Cloud sampling bias — removes artifacts or floating clouds.",
        "impact": "Косметика неба.",
        "impact_en": "Sky cosmetics.",
        "min": "0",
        "max": "10",
        "value_hint": "только при артефактах",
        "value_hint_en": "only for artifacts",
        "category": "Rendering",
        "value_type": "float",
    }
    out["r.Cloud.Count"] = cloud_entry("Count")

    for effect in FX:
        for suffix in ("Enable", "Quality", "Intensity", "Max"):
            out[f"fx.{effect}.{suffix}"] = fx_entry(effect, suffix)

    return out


def main() -> None:
    data = build_all()
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(data)} -> {OUT}")


if __name__ == "__main__":
    main()
