"""Family template entries for tier A expansion v6."""

from __future__ import annotations

FAMILY = {
    "Cloud": {
        "topic_ru": "volumetric облака",
        "topic_en": "volumetric clouds",
        "impact_ru": "Средняя на открытом небе.",
        "impact_en": "Medium under open sky.",
        "cat": "Rendering",
    },
    "Decal": {
        "topic_ru": "декали",
        "topic_en": "decals",
        "impact_ru": "Низкая–средняя на уровнях с декалями.",
        "impact_en": "Low–medium on decal-heavy levels.",
        "cat": "Rendering",
    },
    "Directional": {
        "topic_ru": "направленный свет (солнце)",
        "topic_en": "directional light (sun)",
        "impact_ru": "Сильно на открытых картах и тенях.",
        "impact_en": "Strong on open maps and shadows.",
        "cat": "Rendering",
    },
    "Foliage": {
        "topic_ru": "растительность (foliage)",
        "topic_en": "foliage vegetation",
        "impact_ru": "Средняя–высокая в лесах.",
        "impact_en": "Medium–high in forests.",
        "cat": "Rendering",
    },
    "FXAA": {
        "topic_ru": "FXAA сглаживание",
        "topic_en": "FXAA anti-aliasing",
        "impact_ru": "Низкая нагрузка, может «мыть» картинку.",
        "impact_en": "Low load, may blur the image.",
        "cat": "PostProcess",
    },
    "GlobalIllumination": {
        "topic_ru": "global illumination",
        "topic_en": "global illumination",
        "impact_ru": "Очень высокая на GI-сценах.",
        "impact_en": "Very high on GI-heavy scenes.",
        "cat": "Rendering",
    },
    "Grass": {
        "topic_ru": "трава",
        "topic_en": "grass",
        "impact_ru": "Средняя на лугах и open world.",
        "impact_en": "Medium on meadows and open world.",
        "cat": "Rendering",
    },
    "HeterogeneousVolumes": {
        "topic_ru": "heterogeneous volumes",
        "topic_en": "heterogeneous volumes",
        "impact_ru": "Очень высокая на volumetric FX.",
        "impact_en": "Very high on volumetric FX.",
        "cat": "Rendering",
    },
    "Landscape": {
        "topic_ru": "ландшафт",
        "topic_en": "landscape terrain",
        "impact_ru": "Средняя–высокая на open world.",
        "impact_en": "Medium–high on open world.",
        "cat": "Rendering",
    },
    "Level": {
        "topic_ru": "стриминг уровня",
        "topic_en": "level streaming",
        "impact_ru": "CPU и фризы подгрузки.",
        "impact_en": "CPU and streaming hitches.",
        "cat": "Other",
    },
    "Light": {
        "topic_ru": "освещение",
        "topic_en": "lighting",
        "impact_ru": "Средняя–высокая на ночных уровнях.",
        "impact_en": "Medium–high on night levels.",
        "cat": "Rendering",
    },
    "Lumen": {
        "topic_ru": "Lumen (общий)",
        "topic_en": "Lumen (general)",
        "impact_ru": "Очень высокая в UE5.",
        "impact_en": "Very high in UE5.",
        "cat": "Rendering",
    },
    "Mesh": {
        "topic_ru": "меши и LOD",
        "topic_en": "mesh LOD",
        "impact_ru": "Средняя на плотных уровнях.",
        "impact_en": "Medium on dense levels.",
        "cat": "Rendering",
    },
    "Moon": {
        "topic_ru": "лунный свет",
        "topic_en": "moonlight",
        "impact_ru": "Низкая–средняя ночью.",
        "impact_en": "Low–medium at night.",
        "cat": "Rendering",
    },
    "MotionBlur": {
        "topic_ru": "motion blur",
        "topic_en": "motion blur",
        "impact_ru": "Средняя при быстром движении.",
        "impact_en": "Medium during fast motion.",
        "cat": "PostProcess",
    },
    "Ocean": {
        "topic_ru": "океан",
        "topic_en": "ocean",
        "impact_ru": "Средняя–высокая на водных уровнях.",
        "impact_en": "Medium–high on water levels.",
        "cat": "Rendering",
    },
    "Point": {
        "topic_ru": "точечный свет",
        "topic_en": "point light",
        "impact_ru": "Средняя в интерьерах.",
        "impact_en": "Medium indoors.",
        "cat": "Rendering",
    },
    "Reflections": {
        "topic_ru": "отражения",
        "topic_en": "reflections",
        "impact_ru": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "cat": "Rendering",
    },
    "Render": {
        "topic_ru": "общий рендер",
        "topic_en": "general rendering",
        "impact_ru": "Зависит от параметра.",
        "impact_en": "Depends on parameter.",
        "cat": "Rendering",
    },
    "Scene": {
        "topic_ru": "рендер сцены",
        "topic_en": "scene rendering",
        "impact_ru": "Средняя–высокая.",
        "impact_en": "Medium–high.",
        "cat": "Rendering",
    },
    "Skeletal": {
        "topic_ru": "скелетные меши",
        "topic_en": "skeletal meshes",
        "impact_ru": "Средняя на уровнях с NPC.",
        "impact_en": "Medium on NPC-heavy levels.",
        "cat": "Rendering",
    },
    "Sky": {
        "topic_ru": "небо",
        "topic_en": "sky",
        "impact_ru": "Средняя на открытом небе.",
        "impact_en": "Medium under open sky.",
        "cat": "Rendering",
    },
    "SSGI": {
        "topic_ru": "SSGI",
        "topic_en": "SSGI",
        "impact_ru": "Высокая на GI-сценах.",
        "impact_en": "High on GI scenes.",
        "cat": "Rendering",
    },
    "SSS": {
        "topic_ru": "subsurface scattering",
        "topic_en": "subsurface scattering",
        "impact_ru": "Средняя на персонажах и коже.",
        "impact_en": "Medium on characters and skin.",
        "cat": "Rendering",
    },
    "Star": {
        "topic_ru": "звёздное небо",
        "topic_en": "starfield",
        "impact_ru": "Низкая ночью.",
        "impact_en": "Low at night.",
        "cat": "Rendering",
    },
    "TemporalAA": {
        "topic_ru": "TAA",
        "topic_en": "TAA",
        "impact_ru": "Средняя, может «мыть» в движении.",
        "impact_en": "Medium, may blur in motion.",
        "cat": "PostProcess",
    },
    "Tonemapper": {
        "topic_ru": "tonemapper",
        "topic_en": "tonemapper",
        "impact_ru": "Косметика HDR.",
        "impact_en": "HDR cosmetics.",
        "cat": "PostProcess",
    },
    "Upscale": {
        "topic_ru": "upscaling",
        "topic_en": "upscaling",
        "impact_ru": "Сильно влияет на FPS и резкость.",
        "impact_en": "Strong FPS and sharpness impact.",
        "cat": "PostProcess",
    },
}

SUFFIX = {
    "Enable": {
        "title_ru": "{topic}: вкл/выкл", "title_en": "{topic}: enable",
        "desc_ru": "0 — {topic} отключён или упрощён (FPS). 1 — полная отрисовка.",
        "desc_en": "0 — {topic} off or simplified (FPS). 1 — full rendering.",
        "hint_ru": "0 — FPS, 1 — качество", "hint_en": "0 — FPS, 1 — quality",
        "min": "0", "max": "1", "type": "int",
    },
    "Quality": {
        "title_ru": "{topic}: качество", "title_en": "{topic}: quality",
        "desc_ru": "Уровень качества {topic}. 0 — быстро. 4 — максимум деталей.",
        "desc_en": "{topic} quality. 0 — fast. 4 — max detail.",
        "hint_ru": "2 — баланс", "hint_en": "2 — balance",
        "min": "0", "max": "4", "type": "int",
    },
    "Distance": {
        "title_ru": "{topic}: дальность", "title_en": "{topic}: distance",
        "desc_ru": "Дальность влияния {topic}. Меньше — FPS, больше — видно дальше.",
        "desc_en": "{topic} influence distance. Lower — FPS, higher — farther.",
        "hint_ru": "уменьшить для FPS", "hint_en": "lower for FPS",
        "min": "100", "max": "100000", "type": "float",
    },
    "Intensity": {
        "title_ru": "{topic}: яркость", "title_en": "{topic}: intensity",
        "desc_ru": "Множитель яркости {topic}. 1 — норма.",
        "desc_en": "{topic} brightness multiplier. 1 — normal.",
        "hint_ru": "1 — норма", "hint_en": "1 — normal",
        "min": "0", "max": "4", "type": "float",
    },
    "Max": {
        "title_ru": "{topic}: верхний предел", "title_en": "{topic}: max clamp",
        "desc_ru": "Ограничивает максимум {topic}.",
        "desc_en": "Caps maximum {topic}.",
        "hint_ru": "при пересвете — ниже", "hint_en": "lower if overbright",
        "min": "0", "max": "10", "type": "float",
    },
    "Min": {
        "title_ru": "{topic}: нижний предел", "title_en": "{topic}: min clamp",
        "desc_ru": "Минимальный вклад {topic}.",
        "desc_en": "Minimum {topic} contribution.",
        "hint_ru": "0 — прозрачный минимум", "hint_en": "0 — transparent min",
        "min": "0", "max": "1", "type": "float",
    },
    "Resolution": {
        "title_ru": "{topic}: разрешение", "title_en": "{topic}: resolution",
        "desc_ru": "Разрешение буфера {topic}. Ниже — быстрее.",
        "desc_en": "{topic} buffer resolution. Lower — faster.",
        "hint_ru": "512–1024 — баланс", "hint_en": "512–1024 — balance",
        "min": "128", "max": "4096", "type": "int",
    },
    "Scale": {
        "title_ru": "{topic}: масштаб", "title_en": "{topic}: scale",
        "desc_ru": "Масштаб эффекта {topic}. 1 — стандарт.",
        "desc_en": "{topic} effect scale. 1 — default.",
        "hint_ru": "1 — стандарт", "hint_en": "1 — default",
        "min": "0.1", "max": "4", "type": "float",
    },
    "Size": {
        "title_ru": "{topic}: размер", "title_en": "{topic}: size",
        "desc_ru": "Размер источника {topic} — мягкость переходов.",
        "desc_en": "{topic} source size — transition softness.",
        "hint_ru": "больше — мягче", "hint_en": "higher — softer",
        "min": "0", "max": "100", "type": "float",
    },
    "Threshold": {
        "title_ru": "{topic}: порог", "title_en": "{topic}: threshold",
        "desc_ru": "Порог отсечения {topic} — экономия GPU.",
        "desc_en": "{topic} cutoff threshold — GPU savings.",
        "hint_ru": "не трогать без причины", "hint_en": "leave unless needed",
        "min": "0", "max": "1", "type": "float",
    },
    "Bias": {
        "title_ru": "{topic}: bias", "title_en": "{topic}: bias",
        "desc_ru": "Bias сэмплинга {topic} — против артефактов.",
        "desc_en": "{topic} sampling bias — against artifacts.",
        "hint_ru": "только при артефактах", "hint_en": "only for artifacts",
        "min": "0", "max": "10", "type": "float",
    },
    "Count": {
        "title_ru": "{topic}: число сэмплов", "title_en": "{topic}: sample count",
        "desc_ru": "Число сэмплов {topic}. Больше — плавнее.",
        "desc_en": "{topic} sample count. More — smoother.",
        "hint_ru": "8–16 — баланс", "hint_en": "8–16 — balance",
        "min": "1", "max": "64", "type": "int",
    },
}


def build_family_entry(key: str) -> dict:
    _, family, suffix = key.split(".", 2)
    meta = FAMILY[family]
    suf = SUFFIX[suffix]
    tr, te = meta["topic_ru"], meta["topic_en"]
    return {
        "title": suf["title_ru"].format(topic=tr),
        "title_en": suf["title_en"].format(topic=te),
        "description": suf["desc_ru"].format(topic=tr),
        "description_en": suf["desc_en"].format(topic=te),
        "impact": meta["impact_ru"],
        "impact_en": meta["impact_en"],
        "min": suf["min"],
        "max": suf["max"],
        "value_hint": suf["hint_ru"],
        "value_hint_en": suf["hint_en"],
        "category": meta["cat"],
        "value_type": suf["type"],
    }
