//! Generates `src/lib/api/bindings.ts` from Rust DTOs (run via `npm run types:gen`).

use crate::display::ScreenResolution;
use crate::gpu::GpuCapabilities;
use crate::gpu::types::GpuVendor;
use crate::launch::LaunchResult;
use crate::core::models::{
    ApplyResult, BackupInfo, ConfigDiffEntry, ConfigResetResult, GameConfig, GameOverride,
    GameParameter, GameProfile, IniFileData, ParameterOption,
};
use crate::scalability::ScalabilityLimits;
use specta::Types;
use specta_serde::PhasesFormat;
use specta_typescript::Typescript;

const BINDINGS_PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/api/bindings.ts");

#[test]
fn export_typescript_bindings() {
    let types = Types::default()
        .register::<GameProfile>()
        .register::<GameParameter>()
        .register::<ParameterOption>()
        .register::<ConfigDiffEntry>()
        .register::<ApplyResult>()
        .register::<BackupInfo>()
        .register::<GameConfig>()
        .register::<IniFileData>()
        .register::<ConfigResetResult>()
        .register::<GameOverride>()
        .register::<LaunchResult>()
        .register::<ScreenResolution>()
        .register::<ScalabilityLimits>()
        .register::<GpuVendor>()
        .register::<GpuCapabilities>();

    Typescript::default()
        .header("// Generated by `npm run types:gen` — do not edit manually.\n")
        .export_to(BINDINGS_PATH, &types, PhasesFormat)
        .expect("failed to export TypeScript bindings");
}
